// Smart Daily 全站数据 - 自动生成于 2026-06-28 06:04
// 数据来源：新浪财经、网易新闻、量子位、HackerNews、GitHub、BBC News
const newsData = {
  updateTime: '2026-06-28 06:04',
  ai: [
  {
    "id": "ai-1",
    "title": "BrowserBC：克隆人类点击，让一次网页操作转化为所有Agent的能力",
    "summary": "人类一次录制，Agent就能模拟",
    "content": "人类一次录制，Agent就能模拟",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/439393.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-2",
    "title": "第一批一人公司，现在怎么样了？",
    "summary": "我们跟一群OPC创业者聊了聊",
    "content": "我们跟一群OPC创业者聊了聊",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/439237.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-3",
    "title": "CVPR 2026最热方向，被一家杭州团队率先跑进了端侧！",
    "summary": "VLM- R1之后再次出手！全球首个端侧流式多模态来了！",
    "content": "VLM- R1之后再次出手！全球首个端侧流式多模态来了！",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/439236.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-4",
    "title": "微软年度AI职场报告：员工已经准备好了，公司还没有",
    "summary": "28页干货爆炸",
    "content": "28页干货爆炸",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/439032.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-5",
    "title": "GPT-5.6突然发布！Fable5痛失最强基模王座",
    "summary": "一口气端出三款GPT 5.6系列模型",
    "content": "一口气端出三款GPT 5.6系列模型",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/438895.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-6",
    "title": "两个月连获两轮数亿元融资 深度机智以全栈自主路线加速国产物理AI基座模型落地",
    "summary": "",
    "content": "",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/438887.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-7",
    "title": "谷歌「推理之王」也跑路Meta了，当年还是李飞飞挖来的",
    "summary": "Coding为王",
    "content": "Coding为王",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/438848.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-8",
    "title": "Claude Fable 5分批重新上线！GPT-5.6秒跟",
    "summary": "这不能是营销计划的一部分吧？",
    "content": "这不能是营销计划的一部分吧？",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/438789.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-9",
    "title": "从需求到设计到代码，一个软件全搞定！TRAE Work Design实测来了",
    "summary": "精准识别设计系统",
    "content": "精准识别设计系统",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/438750.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-10",
    "title": "华勤技术与正行创新达成战略合作，加速机器人“走进工厂、走上产线”",
    "summary": "共建工业物理智能“数据底座与智能大脑”",
    "content": "共建工业物理智能“数据底座与智能大脑”",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-28",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/438741.html",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  finance: [
  {
    "id": "fin-1",
    "title": "最新消息！科技巨头，突传利好！",
    "summary": "AI科技巨头，传出利好消息！ 28日，据最新消息，美国政府即将允许Anthropic恢复其最新大模型Fable 5的访问权限。 此前6月12日，美国政府以国家安全为由...",
    "content": "AI科技巨头，传出利好消息！ 28日，据最新消息，美国政府即将允许Anthropic恢复其最新大模型Fable 5的访问权限。 此前6月12日，美国政府以国家安全为由...",
    "category": "财经股市",
    "source": "券商中国",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/world/2026-06-28/doc-iniexucu3935956.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-2",
    "title": "德法或提前相遇！美加墨世界杯32强对阵表来了",
    "summary": "北京时间6月28日，2026年美加墨世界杯J组小组赛收官。阿根廷3-1战胜约旦，阿尔及利亚3-3战平奥地利。阿根廷小组第一，奥地利小组第二，阿尔及利亚小组第三，均出线...",
    "content": "北京时间6月28日，2026年美加墨世界杯J组小组赛收官。阿根廷3-1战胜约旦，阿尔及利亚3-3战平奥地利。阿根廷小组第一，奥地利小组第二，阿尔及利亚小组第三，均出线...",
    "category": "财经股市",
    "source": "央视",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/jjxw/2026-06-28/doc-iniexucw6383585.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-3",
    "title": "谷歌限制了Meta的Gemini使用量，因为人工智能需求激增导致产能紧张",
    "summary": " 英国媒体援引三位知情人士消息称，谷歌在今年3月前后告知Meta，无法足额供应其所需的Gemini模型算力额度。此举打乱并推迟了Meta多项内部人工智能项目的推进节奏。",
    "content": " 英国媒体援引三位知情人士消息称，谷歌在今年3月前后告知Meta，无法足额供应其所需的Gemini模型算力额度。此举打乱并推迟了Meta多项内部人工智能项目的推进节奏。",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-28",
    "icon": "🏢",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-28/doc-iniexucw0700757.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-4",
    "title": "欢乐谷集团联手东方演艺集团、宇树科技等构建“欢乐互联”文旅融合平台",
    "summary": "6月28日消息，在北京欢乐谷20周年庆典暨欢乐谷集团“城市IP娱乐主场”战略发布会上，99米高的“大眼京”摩天轮正式运行，全新银河广场开放迎客...",
    "content": "6月28日消息，在北京欢乐谷20周年庆典暨欢乐谷集团“城市IP娱乐主场”战略发布会上，99米高的“大眼京”摩天轮正式运行，全新银河广场开放迎客...",
    "category": "财经股市",
    "source": "新浪财经",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/china/2026-06-28/doc-iniexucy3150937.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-5",
    "title": "报道：品浩（PIMCO）瞄准公开市场私募交易",
    "summary": " 英国媒体援引对品浩首席投资官的采访报道，品浩正借助部分大型融资方的资金需求，在公开市场开展私募交易以把握投资机遇。",
    "content": " 英国媒体援引对品浩首席投资官的采访报道，品浩正借助部分大型融资方的资金需求，在公开市场开展私募交易以把握投资机遇。",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-28/doc-iniexucy3150425.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-6",
    "title": "腾讯小范围内测TenPay Go，面向境外人士来华支付",
    "summary": " 界面新闻记者了解到，腾讯正在内测一款面向境外人士的“来华生活便利助手”，旨在提供包括移动支付服务的一站式数字生活服务。",
    "content": " 界面新闻记者了解到，腾讯正在内测一款面向境外人士的“来华生活便利助手”，旨在提供包括移动支付服务的一站式数字生活服务。",
    "category": "财经股市",
    "source": "界面",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/jjxw/2026-06-28/doc-iniexpvy0822938.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-7",
    "title": "世界杯 | 32强对阵出炉！日本挑战巴西，梅罗不同半区，亚洲9队仅2队出线",
    "summary": "来源：体坛周报 当地时间6月27日，美加墨世界杯小组赛全部结束。48支参赛队决出32强跻身淘汰赛，传统强队全部晋级。 【1/16决赛对阵】 06.29 03：00南非vs加拿大 06...",
    "content": "来源：体坛周报 当地时间6月27日，美加墨世界杯小组赛全部结束。48支参赛队决出32强跻身淘汰赛，传统强队全部晋级。 【1/16决赛对阵】 06.29 03：00南非vs加拿大 06...",
    "category": "财经股市",
    "source": "市场资讯",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/world/2026-06-28/doc-iniexpvw4045521.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-8",
    "title": "美军对伊朗目标展开新一轮打击 周末交锋后双方互指违反停火协议",
    "summary": "美国周六对伊朗境内多个目标实施了新一轮空袭，此前周末的以牙还牙式攻击令双方均指责对方违反了支撑和谈的停火协议。 周五的首次美军打击是对伊朗周四袭击一艘集装箱船的...",
    "content": "美国周六对伊朗境内多个目标实施了新一轮空袭，此前周末的以牙还牙式攻击令双方均指责对方违反了支撑和谈的停火协议。 周五的首次美军打击是对伊朗周四袭击一艘集装箱船的...",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-28",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-28/doc-iniexpwa3255827.shtml",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  english: [
  {
    "id": "eng-1",
    "title": "2026年雅思考试改革：新增AI口语评估",
    "summary": "雅思官方宣布引入AI辅助口语评分系统，与人工评分相结合，提高评分一致性和效率，预计2027年全球推行。",
    "content": "雅思官方宣布引入AI辅助口语评分系统，与人工评分相结合，提高评分一致性和效率，预计2027年全球推行。",
    "category": "英语学习",
    "source": "IELTS Official",
    "date": "2026-06-28",
    "icon": "📝",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": true
  },
  {
    "id": "eng-2",
    "title": "DeepL推出AI英语学习功能：实时纠错",
    "summary": "DeepL发布全新英语学习模块，利用大模型技术提供实时语法纠错、同义词推荐和语境化学习建议。",
    "content": "DeepL发布全新英语学习模块，利用大模型技术提供实时语法纠错、同义词推荐和语境化学习建议。",
    "category": "英语学习",
    "source": "DeepL",
    "date": "2026-06-28",
    "icon": "🌐",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  },
  {
    "id": "eng-3",
    "title": "牛津词典2026年度词汇候选：'Neuroplasticity'入围",
    "summary": "牛津词典公布2026年度词汇候选名单，'Neuroplasticity'（神经可塑性）等科学词汇入围，反映公众对脑科学关注。",
    "content": "牛津词典公布2026年度词汇候选名单，'Neuroplasticity'（神经可塑性）等科学词汇入围，反映公众对脑科学关注。",
    "category": "英语学习",
    "source": "Oxford Dictionary",
    "date": "2026-06-28",
    "icon": "📖",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": true
  },
  {
    "id": "eng-4",
    "title": "多邻国AI对话教练：模拟真实场景练口语",
    "summary": "Duolingo发布AI对话教练功能，利用GPT-4技术模拟餐厅点餐、面试等真实场景，提供个性化反馈。",
    "content": "Duolingo发布AI对话教练功能，利用GPT-4技术模拟餐厅点餐、面试等真实场景，提供个性化反馈。",
    "category": "英语学习",
    "source": "Duolingo",
    "date": "2026-06-28",
    "icon": "🦉",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  },
  {
    "id": "eng-5",
    "title": "研究：双语者阿尔茨海默病发病延迟5年",
    "summary": "剑桥大学最新研究表明，熟练掌握双语的人群阿尔茨海默病发病时间平均延迟4-5年，学习语言有益大脑健康。",
    "content": "剑桥大学最新研究表明，熟练掌握双语的人群阿尔茨海默病发病时间平均延迟4-5年，学习语言有益大脑健康。",
    "category": "英语学习",
    "source": "Cambridge University",
    "date": "2026-06-28",
    "icon": "🧠",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  }
],
  tech: [
  {
    "id": "tech-1",
    "title": "Marfa Public Radio Puts You to Sleep",
    "summary": "HackerNews 热门讨论，128 赞同，31 条评论。",
    "content": "HackerNews 热门讨论，128 赞同，31 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://www.marfapublicradio.org/podcast/marfa-public-radio-puts-you-to-sleep",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-2",
    "title": "Wayfinder Router: deterministic routing of queries between local and hosted LLM",
    "summary": "HackerNews 热门讨论，24 赞同，1 条评论。",
    "content": "HackerNews 热门讨论，24 赞同，1 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://github.com/itsthelore/wayfinder-router",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-3",
    "title": "Show HN: Decomp Academy – Learn to decompile GameCube games into matching C",
    "summary": "HackerNews 热门讨论，87 赞同，29 条评论。",
    "content": "HackerNews 热门讨论，87 赞同，29 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://decomp-academy.dev",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-4",
    "title": "AMD Strix Halo RDMA Cluster Setup Guide",
    "summary": "HackerNews 热门讨论，92 赞同，15 条评论。",
    "content": "HackerNews 热门讨论，92 赞同，15 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://github.com/kyuz0/amd-strix-halo-vllm-toolboxes/blob/main/rdma_cluster/setup_guide.md",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-5",
    "title": "Anonymous GitHub account mass-dropping undisclosed 0-days",
    "summary": "HackerNews 热门讨论，748 赞同，296 条评论。",
    "content": "HackerNews 热门讨论，748 赞同，296 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://github.com/bikini/exploitarium",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-6",
    "title": "OpenRA",
    "summary": "HackerNews 热门讨论，641 赞同，126 条评论。",
    "content": "HackerNews 热门讨论，641 赞同，126 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://www.openra.net/",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-7",
    "title": "Ancient Tablets Show Markets Worked 4k Years Before Economists Explained Them",
    "summary": "HackerNews 热门讨论，31 赞同，18 条评论。",
    "content": "HackerNews 热门讨论，31 赞同，18 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://thedailyeconomy.org/article/ancient-clay-tablets-show-markets-worked-4000-years-before-economists-explained-them/",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-8",
    "title": "Choosing a Public DNS Resolver",
    "summary": "HackerNews 热门讨论，116 赞同，35 条评论。",
    "content": "HackerNews 热门讨论，116 赞同，35 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-28",
    "icon": "💻",
    "url": "https://evilbit.de/dns-resolver-guide.html",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  science: [
  {
    "id": "sci-1",
    "title": "I hear my son crying beneath the rubble, says Venezuela earthquake survivor",
    "summary": "Andreina Valerio says she fears for her son, who is trapped with her partner and in-laws beneath a collapsed building.",
    "content": "Andreina Valerio says she fears for her son, who is trapped with her partner and in-laws beneath a collapsed building.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "🔬",
    "url": "https://www.bbc.co.uk/news/articles/ckg4zz90wk7o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-2",
    "title": "Could legal 'personhood' help save Lough Neagh?",
    "summary": "Rights of Nature could give Lough Neagh the same status as a person, entitled to the same protections.",
    "content": "Rights of Nature could give Lough Neagh the same status as a person, entitled to the same protections.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "🔬",
    "url": "https://www.bbc.co.uk/news/articles/cvg7vy307xlo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-3",
    "title": "Europe's deadly heatwave breaks German record and halts public events",
    "summary": "Germany's highest ever temperature of 41.3C is recorded provisionally in Saarbrücken, over the border from France.",
    "content": "Germany's highest ever temperature of 41.3C is recorded provisionally in Saarbrücken, over the border from France.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "🔬",
    "url": "https://www.bbc.co.uk/news/articles/cx2knzzwprgo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-4",
    "title": "Amber extreme heat warning extended before cooldown ends record-breaking heatwave",
    "summary": "The record-breaking heatwave is set to end with cooler and more unsettled weather by \nSunday.",
    "content": "The record-breaking heatwave is set to end with cooler and more unsettled weather by \nSunday.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "🔬",
    "url": "https://www.bbc.co.uk/weather/articles/crkvl343jj3o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-5",
    "title": "Are we in for a summer of serial heatwaves?",
    "summary": "Forecasters have suggested that summer is likely to be warmer than average with an increased chance of more heatwaves, as Simon King explains.",
    "content": "Forecasters have suggested that summer is likely to be warmer than average with an increased chance of more heatwaves, as Simon King explains.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "🔬",
    "url": "https://www.bbc.co.uk/weather/articles/cgrk4w57e74o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-6",
    "title": "Future generations being failed if more trees not planted, experts say",
    "summary": "Statistics show the number of trees being planted is increasing, but conservationists say it is not meeting targets.",
    "content": "Statistics show the number of trees being planted is increasing, but conservationists say it is not meeting targets.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "🔬",
    "url": "https://www.bbc.co.uk/news/articles/c70yj76n4dko?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  knowledge: [
  {
    "id": "know-1",
    "title": "I hear my son crying beneath the rubble, says Venezuela earthquake survivor",
    "summary": "Andreina Valerio says she fears for her son, who is trapped with her partner and in-laws beneath a collapsed building.",
    "content": "Andreina Valerio says she fears for her son, who is trapped with her partner and in-laws beneath a collapsed building.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "📚",
    "url": "https://www.bbc.co.uk/news/articles/ckg4zz90wk7o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-2",
    "title": "Could legal 'personhood' help save Lough Neagh?",
    "summary": "Rights of Nature could give Lough Neagh the same status as a person, entitled to the same protections.",
    "content": "Rights of Nature could give Lough Neagh the same status as a person, entitled to the same protections.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "📚",
    "url": "https://www.bbc.co.uk/news/articles/cvg7vy307xlo?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-3",
    "title": "Europe's deadly heatwave breaks German record and halts public events",
    "summary": "Germany's highest ever temperature of 41.3C is recorded provisionally in Saarbrücken, over the border from France.",
    "content": "Germany's highest ever temperature of 41.3C is recorded provisionally in Saarbrücken, over the border from France.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "📚",
    "url": "https://www.bbc.co.uk/news/articles/cx2knzzwprgo?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-4",
    "title": "Amber extreme heat warning extended before cooldown ends record-breaking heatwave",
    "summary": "The record-breaking heatwave is set to end with cooler and more unsettled weather by \nSunday.",
    "content": "The record-breaking heatwave is set to end with cooler and more unsettled weather by \nSunday.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "📚",
    "url": "https://www.bbc.co.uk/weather/articles/crkvl343jj3o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-5",
    "title": "Are we in for a summer of serial heatwaves?",
    "summary": "Forecasters have suggested that summer is likely to be warmer than average with an increased chance of more heatwaves, as Simon King explains.",
    "content": "Forecasters have suggested that summer is likely to be warmer than average with an increased chance of more heatwaves, as Simon King explains.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "📚",
    "url": "https://www.bbc.co.uk/weather/articles/cgrk4w57e74o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-6",
    "title": "Future generations being failed if more trees not planted, experts say",
    "summary": "Statistics show the number of trees being planted is increasing, but conservationists say it is not meeting targets.",
    "content": "Statistics show the number of trees being planted is increasing, but conservationists say it is not meeting targets.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-28",
    "icon": "📚",
    "url": "https://www.bbc.co.uk/news/articles/c70yj76n4dko?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  }
],
  sports: [
  {
    "id": "sport-1",
    "title": "韩国可算确定被淘汰了",
    "summary": "之前韩国队在那里算分，一会儿这个小组结果一会儿那个小组结果，",
    "content": "之前韩国队在那里算分，一会儿这个小组结果一会儿那个小组结果，",
    "category": "体育",
    "source": "张佳玮写字的地方",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "https://3g.163.com/news/article/L0GO97DI0521ABE4.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-2",
    "title": "世界杯-葡萄牙0-0哥伦比亚!第2出线 桑切斯进球被吹",
    "summary": "网易体育6月28日报道：北京时间6月28日上午7点30分，2",
    "content": "网易体育6月28日报道：北京时间6月28日上午7点30分，2",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/L0GHRVU800058781.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-3",
    "title": "世界杯-阿根廷3-1约旦 小组赛全胜晋级",
    "summary": "网易体育6月28日报道：北京时间6月28日上午10点，202",
    "content": "网易体育6月28日报道：北京时间6月28日上午10点，202",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/L0GQCKSC00058781.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-4",
    "title": "韩国被淘汰！世界杯：民主刚果3-1逆转乌兹别克晋级，维萨2球",
    "summary": "北京时间6月28日07:30，世界杯小组赛K组第3轮，民主刚",
    "content": "北京时间6月28日07:30，世界杯小组赛K组第3轮，民主刚",
    "category": "体育",
    "source": "乒烧泳球",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-5",
    "title": "终于拔管 韩国正式宣告世界杯小组出局 煎熬3天等待：连收7个噩耗",
    "summary": "在北京时间6月28日结束的世界杯K组末轮1场焦点战中，民主刚",
    "content": "在北京时间6月28日结束的世界杯K组末轮1场焦点战中，民主刚",
    "category": "体育",
    "source": "我爱英超",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-6",
    "title": "世界杯-英格兰2-0巴拿马头名晋级 贝林厄姆传射凯恩进球",
    "summary": "网易体育6月28日报道：北京时间6月28日凌晨5点整，202",
    "content": "网易体育6月28日报道：北京时间6月28日凌晨5点整，202",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/L0G93BLN00058781.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-7",
    "title": "苏契奇世界波队史第2人，魔笛制胜助攻，克罗地亚2-1加纳携手晋级",
    "summary": "正处于新老交替期的克罗地亚，在本届世界杯第一轮输给英格兰之后",
    "content": "正处于新老交替期的克罗地亚，在本届世界杯第一轮输给英格兰之后",
    "category": "体育",
    "source": "钉钉陌上花开",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-8",
    "title": "记者：乌拉圭足协决定取消包机，球员将乘坐普通航班返回",
    "summary": "据乌拉圭记者MartinCharquero的消息，乌拉圭足协",
    "content": "据乌拉圭记者MartinCharquero的消息，乌拉圭足协",
    "category": "体育",
    "source": "懂球帝",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-9",
    "title": "官方：马宁将担任世界杯1/16决赛德国vs巴拉圭第四官员",
    "summary": "国际足联官方公布了世界杯1/16决赛德国对阵巴拉圭的裁判组名",
    "content": "国际足联官方公布了世界杯1/16决赛德国对阵巴拉圭的裁判组名",
    "category": "体育",
    "source": "懂球帝",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-10",
    "title": "巴媒：佛得角队长瑞安-门德斯涉嫌强奸，新西兰警方正在调查",
    "summary": "据巴西《环球报》报道，新西兰警方已就佛得角队长瑞安-门德斯涉",
    "content": "据巴西《环球报》报道，新西兰警方已就佛得角队长瑞安-门德斯涉",
    "category": "体育",
    "source": "懂球帝",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-11",
    "title": "昔日6号秀遭放弃！魔术正式裁掉艾萨克 节省650万美元奢侈税",
    "summary": "北京时间6月28日，联盟消息人士向《奥兰多哨兵报》证实，魔术",
    "content": "北京时间6月28日，联盟消息人士向《奥兰多哨兵报》证实，魔术",
    "category": "体育",
    "source": "罗说NBA",
    "date": "2026-06-28",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-12",
    "title": "曝八村垒最可能离开湖人！马刺篮网有意签下他：或搭档文班冲冠",
    "summary": "北京时间6月28日，湖人队内多名到期自由球员中，下赛季最有可",
    "content": "北京时间6月28日，湖人队内多名到期自由球员中，下赛季最有可",
    "category": "体育",
    "source": "罗说NBA",
    "date": "2026-06-28",
    "icon": "🏀",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  entertainment: [
  {
    "id": "ent-1",
    "title": "白玉兰奖落幕，唯她被骂惨",
    "summary": "今年的白玉兰奖，可比往年热闹太多了，奖项刚落定，整个娱乐圈就",
    "content": "今年的白玉兰奖，可比往年热闹太多了，奖项刚落定，整个娱乐圈就",
    "category": "娱乐",
    "source": "深析古今",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0GI89N605568PHC.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-2",
    "title": "白玉兰奖成照妖镜？杨紫得奖，杨幂受牵连",
    "summary": "每年白玉兰颁奖，台下的戏都比台上的颁奖好看一万倍。名利场扎堆",
    "content": "每年白玉兰颁奖，台下的戏都比台上的颁奖好看一万倍。名利场扎堆",
    "category": "娱乐",
    "source": "小嵩",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0GHVFNJ0556AYQW.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-3",
    "title": "胡歌白玉兰空手而归，输给的是对演员的执念",
    "summary": "【白玉兰颁奖现场，胡歌坐在台下微笑鼓掌】6月26日晚，白玉兰",
    "content": "【白玉兰颁奖现场，胡歌坐在台下微笑鼓掌】6月26日晚，白玉兰",
    "category": "娱乐",
    "source": "可乐谈情感",
    "date": "2026-06-28",
    "icon": "⭐",
    "url": "https://3g.163.com/news/article/L0GGKJT30553VGXP.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-4",
    "title": "霍尊这次要把陈露送进去！？",
    "summary": "之前疯叔就说了，陈露又开始跳出来搞事情捶霍尊。最近她又联合狗",
    "content": "之前疯叔就说了，陈露又开始跳出来搞事情捶霍尊。最近她又联合狗",
    "category": "娱乐",
    "source": "八卦疯叔",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0EKP6AV05524KLP.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-5",
    "title": "瞒不住了！38岁刘亦菲高调官宣喜讯",
    "summary": "在乱象丛生的内娱，刘亦菲绝对是独一份的存在，38岁的她依旧撑",
    "content": "在乱象丛生的内娱，刘亦菲绝对是独一份的存在，38岁的她依旧撑",
    "category": "娱乐",
    "source": "原梦叁生",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0GG4DLU0556BNMO.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-6",
    "title": "老演员太朴实无华！董勇获白玉兰：攥奖杯啃桃酥",
    "summary": "拿着沉甸甸的白玉兰奖杯，别人都在忙着红毯摆拍、后台合影，他却",
    "content": "拿着沉甸甸的白玉兰奖杯，别人都在忙着红毯摆拍、后台合影，他却",
    "category": "娱乐",
    "source": "南万说娱26",
    "date": "2026-06-28",
    "icon": "⭐",
    "url": "https://3g.163.com/news/article/L0GGAS4N0556KOU0.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-7",
    "title": "冯小刚新片彻底扑街！袁立犀利发文不留情面",
    "summary": "曾经的冯小刚，是华语影坛当之无愧的贺岁档王者，手握多部经典爆",
    "content": "曾经的冯小刚，是华语影坛当之无愧的贺岁档王者，手握多部经典爆",
    "category": "娱乐",
    "source": "无处不风景love",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0GGHL6L0517HIAS.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-8",
    "title": "海清现身周杰伦演唱会，儿子浑身肌肉",
    "summary": "周杰伦演唱会向来是明星扎堆的名场面，不少圈内艺人都会悄悄到场",
    "content": "周杰伦演唱会向来是明星扎堆的名场面，不少圈内艺人都会悄悄到场",
    "category": "娱乐",
    "source": "晓銊就是我",
    "date": "2026-06-28",
    "icon": "🎵",
    "url": "https://3g.163.com/news/article/L0GIV5SF0556CU5L.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-9",
    "title": "《千香》开播首日，观众弃剧一片理由一致",
    "summary": "娱乐圈从来不缺资源咖，但很少有人能像鞠婧祎这样，手握源源不断",
    "content": "娱乐圈从来不缺资源咖，但很少有人能像鞠婧祎这样，手握源源不断",
    "category": "娱乐",
    "source": "书慧我心",
    "date": "2026-06-28",
    "icon": "📽️",
    "url": "https://3g.163.com/news/article/L0GIQRDT0556CICS.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-10",
    "title": "说“提名靠努力，得奖靠运气”的吴越，真的很美",
    "summary": "2026年6月26日晚，第31届上海电视节白玉兰奖落下帷幕，",
    "content": "2026年6月26日晚，第31届上海电视节白玉兰奖落下帷幕，",
    "category": "娱乐",
    "source": "澎湃新闻",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0GG4LUK0514R9P4.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-11",
    "title": "第37届金曲奖，蔡依林封后，斩获金曲奖三项大奖",
    "summary": "蔡依林直接创下一个几乎没人能打破的纪录，第37届金曲奖，蔡依",
    "content": "蔡依林直接创下一个几乎没人能打破的纪录，第37届金曲奖，蔡依",
    "category": "娱乐",
    "source": "爱吃冰棍的小痞子",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0FPTF7S05563YDU.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-12",
    "title": "大衣哥再次登上热搜！演出后聚餐，面前放满白酒",
    "summary": "六月的菏泽，热得人不想动。路边的饭馆不大，塑料门帘掀起来，里",
    "content": "六月的菏泽，热得人不想动。路边的饭馆不大，塑料门帘掀起来，里",
    "category": "娱乐",
    "source": "喜欢历史的阿繁",
    "date": "2026-06-28",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/L0GH1BU305566SC3.html",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  international: [
  {
    "id": "intl-1",
    "title": "'Every person saved is a miracle': Families call to trapped loved ones in region devastated by Venezuela quakes",
    "summary": "Families keep vigil at buildings where they fear their loved ones are trapped, but face an impossible task to move heavy debris.",
    "content": "Families keep vigil at buildings where they fear their loved ones are trapped, but face an impossible task to move heavy debris.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cp8l451420zo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-2",
    "title": "In Caracas, this feels like the hardest moment in Venezuela's modern history",
    "summary": "Rescue teams are working ceaselessly to reach those trapped under rubble. But as hope fades, anger is growing.",
    "content": "Rescue teams are working ceaselessly to reach those trapped under rubble. But as hope fades, anger is growing.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cdjk8zwe7z3o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-3",
    "title": "US and Iran exchange strikes and accuse each other of violating ceasefire",
    "summary": "Iran says it has launched retaliatory attacks at US infrastructure in Kuwait and Bahrain after the US said it hit multiple targets across Iran.",
    "content": "Iran says it has launched retaliatory attacks at US infrastructure in Kuwait and Bahrain after the US said it hit multiple targets across Iran.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cdxdwkgqgq0o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-4",
    "title": "Israel strikes southern Lebanon as Hezbollah condemns new deal",
    "summary": "Strikes have killed at least one person, state media say a day after Lebanon and Israel signed a framework agreement.",
    "content": "Strikes have killed at least one person, state media say a day after Lebanon and Israel signed a framework agreement.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cx2kpn0eeweo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-5",
    "title": "Why Kim Jong Un never talks about his mother - or her controversial bloodline",
    "summary": "Very few North Koreans know about her, as her origin could threaten the regime’s legitimacy.",
    "content": "Very few North Koreans know about her, as her origin could threaten the regime’s legitimacy.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cpvp3xn489no?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-6",
    "title": "Heatwave breaks records in Germany, Denmark and Czech Republic",
    "summary": "An estimated 150 million people are now experiencing temperatures of over 35C across Europe.",
    "content": "An estimated 150 million people are now experiencing temperatures of over 35C across Europe.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cx2vdydz31no?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-7",
    "title": "Trump's face is added to select US passports for America's 250th birthday",
    "summary": "The commemorative special edition passports will be available on 6 July, and can only be applied for in person",
    "content": "The commemorative special edition passports will be available on 6 July, and can only be applied for in person",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/ce3ewkdgw9ro?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-8",
    "title": "Religion row as Texas makes Bible stories required reading in schools",
    "summary": "Critics say the new reading requirements infringe on religious freedoms and blur the separation of church and state.",
    "content": "Critics say the new reading requirements infringe on religious freedoms and blur the separation of church and state.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/ckg8m2xkg84o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-9",
    "title": "Burkina Faso severs diplomatic ties with France",
    "summary": "The West African country's junta accused the former colonial power of undermining its national interests.",
    "content": "The West African country's junta accused the former colonial power of undermining its national interests.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/c7vymlgl5vgo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-10",
    "title": "Meloni and Trump: A very public fall-out that is proving very hard to fix",
    "summary": "Italy's PM was not long ago being called the \"Trump whisperer\", but their relationship has gone from public attacks to personal insults.",
    "content": "Italy's PM was not long ago being called the \"Trump whisperer\", but their relationship has gone from public attacks to personal insults.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cze962pgk27o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-11",
    "title": "Billionaire Leon Black walks out of Epstein investigation hearing",
    "summary": "The House panel then issued subpoenas demanding the private equity tycoon, who co-founded Apollo Global Management, testify on camera and under oath.",
    "content": "The House panel then issued subpoenas demanding the private equity tycoon, who co-founded Apollo Global Management, testify on camera and under oath.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cn948lwyl3jo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-12",
    "title": "Pete Buttigieg briefly separated from children after false police report",
    "summary": "Buttigieg says the day he spent separated from his twins was \"among the darkest hours of my life\".",
    "content": "Buttigieg says the day he spent separated from his twins was \"among the darkest hours of my life\".",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-28",
    "icon": "🌍",
    "url": "https://www.bbc.co.uk/news/articles/cwydx95kjx0o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  history: [
    { id: 'his-1', title: '经典论文回顾：Attention Is All You Need（2017）', summary: 'Transformer架构的开创性论文，彻底改变了NLP领域，奠定了现代大语言模型的基础，被引用超过15万次。', category: '经典回顾', source: 'arXiv', date: '2017-06-12', icon: '📄', url: 'https://arxiv.org/abs/1706.03762', readTime: '15 分钟', isHot: false },
    { id: 'his-2', title: '经典论文回顾：ImageNet Classification with Deep CNN（2012）', summary: 'AlexNet论文，深度学习在计算机视觉领域的里程碑，首次证明深度CNN在图像识别中的巨大优势。', category: '经典回顾', source: 'NeurIPS', date: '2012-12-03', icon: '📷', url: 'https://papers.nips.cc', readTime: '12 分钟', isHot: false },
    { id: 'his-3', title: '经典著作：本杰明·格雷厄姆《聪明的投资者》（1949）', summary: '价值投资圣经，巴菲特称之为有史以来最好的投资书籍，阐述了安全边际、市场先生等核心理念。', category: '经典回顾', source: 'Harper & Brothers', date: '1949-01-01', icon: '📚', url: 'https://www.amazon.com', readTime: '30 分钟', isHot: false },
    { id: 'his-4', title: '里程碑：AlphaGo击败李世石（2016）', summary: 'DeepMind的AlphaGo以4:1击败世界围棋冠军李世石，标志着AI在复杂策略游戏中超越人类。', category: '经典回顾', source: 'Nature', date: '2016-03-15', icon: '⚫', url: 'https://www.nature.com', readTime: '10 分钟', isHot: false },
    { id: 'his-5', title: '经典论文回顾：Bitcoin白皮书（2008）', summary: '中本聪发布的比特币白皮书，开创了加密货币和区块链技术的新纪元，彻底改变了金融科技领域。', category: '经典回顾', source: 'Bitcoin.org', date: '2008-10-31', icon: '₿', url: 'https://bitcoin.org/bitcoin.pdf', readTime: '20 分钟', isHot: false },
    { id: 'his-6', title: '经典著作：瑞·达利欧《原则》（2017）', summary: '桥水基金创始人瑞·达利欧分享其生活与工作原则，包括极度求真、极度透明等核心理念，影响深远。', category: '经典回顾', source: 'Simon & Schuster', date: '2017-09-19', icon: '📖', url: 'https://www.principles.com', readTime: '25 分钟', isHot: false }
  ]
};

const hotTopics = [
  {
    "rank": 1,
    "title": "最新消息！科技巨头，突传利好！",
    "category": "财经股市",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 2,
    "title": "德法或提前相遇！美加墨世界杯32强对阵表来了",
    "category": "财经股市",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 3,
    "title": "谷歌限制了Meta的Gemini使用量，因为人工智能需求激增导致产能紧张",
    "category": "财经股市",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 4,
    "title": "BrowserBC：克隆人类点击，让一次网页操作转化为所有Agent的能力",
    "category": "AI 技术",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 5,
    "title": "第一批一人公司，现在怎么样了？",
    "category": "AI 技术",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 6,
    "title": "CVPR 2026最热方向，被一家杭州团队率先跑进了端侧！",
    "category": "AI 技术",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 7,
    "title": "微软年度AI职场报告：员工已经准备好了，公司还没有",
    "category": "AI 技术",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 8,
    "title": "Marfa Public Radio Puts You to Sleep",
    "category": "计算机",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 9,
    "title": "Wayfinder Router: deterministic routing of queries between local and hosted LLM",
    "category": "计算机",
    "time": "2026-06-28",
    "hot": true
  },
  {
    "rank": 10,
    "title": "Show HN: Decomp Academy – Learn to decompile GameCube games into matching C",
    "category": "计算机",
    "time": "2026-06-28",
    "hot": true
  }
];

const wordData = [
  { word: 'serendipity', phonetic: '/ˌser.ənˈdɪp.ə.ti/', meaning: '意外发现珍宝的运气；机缘凑巧', example: 'The discovery of penicillin was a moment of pure serendipity.', exampleTrans: '青霉素的发现纯粹是机缘巧合。' },
  { word: 'ephemeral', phonetic: '/ɪˈfem.ər.əl/', meaning: '短暂的；转瞬即逝的', example: 'Fashion is ephemeral, changing with every season.', exampleTrans: '时尚是短暂的，每季都在变化。' },
  { word: 'resilience', phonetic: '/rɪˈzɪl.jəns/', meaning: '韧性；恢复力；弹力', example: 'The resilience of the economy surprised many analysts.', exampleTrans: '经济的韧性让许多分析师感到惊讶。' },
  { word: 'paradigm', phonetic: '/ˈpær.ə.daɪm/', meaning: '典范；范例；模式', example: 'The new research represents a paradigm shift in our understanding.', exampleTrans: '这项新研究代表了我们在理解上的范式转变。' },
  { word: 'ubiquitous', phonetic: '/juːˈbɪk.wɪ.təs/', meaning: '无处不在的；十分普遍的', example: 'Smartphones have become ubiquitous in modern society.', exampleTrans: '智能手机在现代社会已经无处不在。' },
  { word: 'pragmatic', phonetic: '/præɡˈmæt.ɪk/', meaning: '务实的；实用的', example: 'We need a pragmatic approach to solve this problem.', exampleTrans: '我们需要一种务实的方法来解决这个问题。' },
  { word: 'innovation', phonetic: '/ˌɪn.əˈveɪ.ʃən/', meaning: '创新；革新；新方法', example: 'Technological innovation drives economic growth.', exampleTrans: '技术创新推动经济增长。' },
  { word: 'sustainable', phonetic: '/səˈsteɪ.nə.bəl/', meaning: '可持续的；能长期维持的', example: 'We must develop sustainable energy solutions.', exampleTrans: '我们必须开发可持续的能源解决方案。' },
  { word: 'algorithm', phonetic: '/ˈæl.ɡə.rɪ.ðəm/', meaning: '算法；计算程序', example: 'The recommendation algorithm personalizes content for each user.', exampleTrans: '推荐算法为每个用户个性化内容。' },
  { word: 'collaboration', phonetic: '/kəˌlæb.əˈreɪ.ʃən/', meaning: '合作；协作', example: 'International collaboration is essential for climate action.', exampleTrans: '国际合作对于气候行动至关重要。' }
];

const sentenceData = [
  { en: 'The only way to do great work is to love what you do.', cn: '成就伟大工作的唯一途径是热爱你所做的事。', source: 'Steve Jobs', tag: '励志' },
  { en: 'Innovation distinguishes between a leader and a follower.', cn: '创新决定一个人是领袖还是跟随者。', source: 'Steve Jobs', tag: '创新' },
  { en: 'The future belongs to those who believe in the beauty of their dreams.', cn: '未来属于那些相信梦想之美的人。', source: 'Eleanor Roosevelt', tag: '梦想' },
  { en: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', cn: '成功不是终点，失败也不是末日：继续前进的勇气才是最重要的。', source: 'Winston Churchill', tag: '坚持' },
  { en: 'The best time to plant a tree was 20 years ago. The second best time is now.', cn: '种一棵树最好的时间是二十年前，其次是现在。', source: 'Chinese Proverb', tag: '行动' },
  { en: 'In the middle of difficulty lies opportunity.', cn: '困境之中蕴藏着机遇。', source: 'Albert Einstein', tag: '机遇' },
  { en: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', cn: '生命中最伟大的荣耀不在于从不跌倒，而在于每次跌倒后都能站起来。', source: 'Nelson Mandela', tag: '坚韧' },
  { en: 'It does not matter how slowly you go as long as you do not stop.', cn: '只要你不停止，走得多慢都没关系。', source: 'Confucius', tag: '毅力' }
];

const newsVocabData = [
  { word: 'surge', meaning: '激增；暴涨', context: 'Stock prices surged after the earnings report.' },
  { word: 'volatile', meaning: '波动的；不稳定的', context: 'The market remains volatile amid geopolitical tensions.' },
  { word: 'merger', meaning: '合并；兼并', context: 'The merger between the two tech giants was approved.' },
  { word: 'dividend', meaning: '股息；红利', context: 'The company announced a quarterly dividend of $0.50.' },
  { word: 'recession', meaning: '经济衰退', context: 'Economists debate whether a recession is imminent.' },
  { word: 'inflation', meaning: '通货膨胀', context: 'Inflation cooled to 2.5% in the latest report.' },
  { word: 'bullish', meaning: '看涨的；乐观的', context: 'Analysts are bullish on AI stocks this quarter.' },
  { word: 'bearish', meaning: '看跌的；悲观的', context: 'Some investors remain bearish on the housing market.' },
  { word: 'liquidity', meaning: '流动性', context: 'The central bank injected liquidity into the market.' },
  { word: 'portfolio', meaning: '投资组合', context: 'Diversification is key to a healthy portfolio.' },
  { word: 'benchmark', meaning: '基准；标杆', context: 'The fund outperformed its benchmark by 3%.' },
  { word: 'valuation', meaning: '估值', context: "The startup's valuation reached $10 billion." }
];
