// Smart Daily 全站数据 - 自动生成于 2026-06-17 06:56
// 数据来源：新浪财经、网易新闻、量子位、HackerNews、GitHub、BBC News
const newsData = {
  updateTime: '2026-06-17 06:56',
  ai: [
  {
    "id": "ai-1",
    "title": "六连冠！文远知行再度刷新中国智驾大赛连胜纪录",
    "summary": "转载来源：文远知行\n本文为量子位获授权转载，观点仅为原作者所有。",
    "content": "转载来源：文远知行\n本文为量子位获授权转载，观点仅为原作者所有。",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/436130.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-2",
    "title": "天工3.1 重磅发布：上线 Skywork Design 与 Dynamic Workflows，给 AI 一张画布和一支军团",
    "summary": "天工超级智能体的收入实现了三倍增长",
    "content": "天工超级智能体的收入实现了三倍增长",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/436110.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-3",
    "title": "刚刚，Fable-5之下，智谱开源的GLM-5.2拿下AI编程第一！",
    "summary": "1M上下文",
    "content": "1M上下文",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/436085.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-4",
    "title": "英特尔晒出未来芯片”三张底牌”：CFET、氮化镓+硅集成、钌互连",
    "summary": "详解制程节点里程碑与未来技术创新",
    "content": "详解制程节点里程碑与未来技术创新",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/436082.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-5",
    "title": "许锦波率分子之心完成逾亿美元融资，定义全球AI蛋白质产业新基建",
    "summary": "世界级科学家领跑AI蛋白第二次范式革命",
    "content": "世界级科学家领跑AI蛋白第二次范式革命",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/436077.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-6",
    "title": "一个模型控制手脚腰身！机器人终于学会全身协同干精细活了",
    "summary": "手的问题，其实不在手",
    "content": "手的问题，其实不在手",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/436073.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-7",
    "title": "和朱广权同台讲脱口秀，鸿蒙小艺这次把AI助手卷到新阶段了？！",
    "summary": "会思考、能调度、还会自进化",
    "content": "会思考、能调度、还会自进化",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435953.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-8",
    "title": "网易有道首席科学家段亦涛：让AI技术扎根业务场景",
    "summary": "转载来源：网易有道\n本文为量子位获授权转载，观点仅为原作者所有。",
    "content": "转载来源：网易有道\n本文为量子位获授权转载，观点仅为原作者所有。",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435950.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-9",
    "title": "不儿，罗永浩、胡彦斌都来参加这场AI大赛了啊",
    "summary": "100万奖金，0门槛参赛",
    "content": "100万奖金，0门槛参赛",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435931.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-10",
    "title": "SpaceX华人女孩刷屏！没有硕博学位，6年从火箭小白到「猛禽」飞行操作员",
    "summary": "她并不是一位被神话出来的「星舰女王」",
    "content": "她并不是一位被神话出来的「星舰女王」",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-17",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435882.html",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  finance: [
  {
    "id": "fin-1",
    "title": "吴清：证监会打击违法违规跨境展业，支持投资者依法合规跨境投资活动",
    "summary": "证监会主席吴清6月17日在2026陆家嘴论坛上表示，着力提升跨境监管协作力度。“近期，我们会同有关方面坚决查处了个别机构违法违规跨境展业等问题。",
    "content": "证监会主席吴清6月17日在2026陆家嘴论坛上表示，着力提升跨境监管协作力度。“近期，我们会同有关方面坚决查处了个别机构违法违规跨境展业等问题。",
    "category": "财经股市",
    "source": "中证网",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/china/2026-06-17/doc-inictaen8880074.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-2",
    "title": "野村：当前财季批发业务收入增长30% 主要受股票产品推动",
    "summary": " 野村控股表示，核心交易和投资银行业务的收入本财季以来大幅增长，表明此前推动该公司去年录得创纪录利润的势头还在持续。",
    "content": " 野村控股表示，核心交易和投资银行业务的收入本财季以来大幅增长，表明此前推动该公司去年录得创纪录利润的势头还在持续。",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-17/doc-inictaet3810621.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-3",
    "title": "英国5月通胀率意外持稳于2.8% 支持央行采取观望策略",
    "summary": "英国5月通胀率出人意料地保持稳定，表明即使在美伊达成和平协议推动能源价格大跌之前，价格压力就已比担心的要小。 英国国家统计局周三公布...",
    "content": "英国5月通胀率出人意料地保持稳定，表明即使在美伊达成和平协议推动能源价格大跌之前，价格压力就已比担心的要小。 英国国家统计局周三公布...",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-17",
    "icon": "🏦",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-17/doc-inictaet3810079.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-4",
    "title": "“大空头”伯里：想做空SpaecX，但太贵了",
    "summary": "因成功预测2008年美国房地产市场崩盘而闻名的投资者迈克尔·伯里周二表示，他曾想做空埃隆·马斯克的SpaceX公司，但最终还是放弃了这个想法，原因是看跌期权成本过高...",
    "content": "因成功预测2008年美国房地产市场崩盘而闻名的投资者迈克尔·伯里周二表示，他曾想做空埃隆·马斯克的SpaceX公司，但最终还是放弃了这个想法，原因是看跌期权成本过高...",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-17/doc-inictaeq5652279.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-5",
    "title": "哪吒汽车方运舟、张勇合计1.16亿元股权遭冻结",
    "summary": "6月17日，据天眼查公开法律诉讼信息显示，桐乡合创德力贰企业管理咨询合伙企业（有限合伙）新增两则股权冻结信息，被执行人分别为哪吒汽车创始人方运舟与原CEO张勇...",
    "content": "6月17日，据天眼查公开法律诉讼信息显示，桐乡合创德力贰企业管理咨询合伙企业（有限合伙）新增两则股权冻结信息，被执行人分别为哪吒汽车创始人方运舟与原CEO张勇...",
    "category": "财经股市",
    "source": "界面",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/jjxw/2026-06-17/doc-inictaet3809396.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-6",
    "title": "航运数据显示至少三艘伊朗邮轮突破霍尔木兹海峡封锁",
    "summary": "至少三艘伊朗油轮载着近500万桶原油，已突破美国海军在霍尔木兹海峡的封锁，这是两个月来首次出现此类外运船队。船东们正谨慎调整运力部署...",
    "content": "至少三艘伊朗油轮载着近500万桶原油，已突破美国海军在霍尔木兹海峡的封锁，这是两个月来首次出现此类外运船队。船东们正谨慎调整运力部署...",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-17/doc-inicsvwt7140641.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-7",
    "title": "华创证券：汇量科技首次覆盖给予“强推”评级 目标价17.7港元",
    "summary": "华创证券发布研报称，汇量科技（01860）是全球第三方程序化广告头部厂商之一，网络效应和AI Infra共振构筑增长飞轮，该行看好公司在全球第三方程序化广告市场中的增长潜力...",
    "content": "华创证券发布研报称，汇量科技（01860）是全球第三方程序化广告头部厂商之一，网络效应和AI Infra共振构筑增长飞轮，该行看好公司在全球第三方程序化广告市场中的增长潜力...",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/hkgg/2026-06-17/doc-inicsvws5755318.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-8",
    "title": "中信里昂：中国海洋石油目标价上调至36港元 重申“跑赢大市”评级",
    "summary": " 中信里昂发布研报称，上调中国海洋石油（00883）H股目标价12.5%，从32港元升至36港元，亦上调A股目标价，重申跑赢大市评级。",
    "content": " 中信里昂发布研报称，上调中国海洋石油（00883）H股目标价12.5%，从32港元升至36港元，亦上调A股目标价，重申跑赢大市评级。",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-17",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/hkgg/2026-06-17/doc-inicsvws5754373.shtml",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  english: [
  {
    "id": "eng-1",
    "title": "2026年雅思考试改革：新增AI口语评估",
    "summary": "雅思官方宣布引入AI辅助口语评分系统，与人工评分相结合，提高评分一致性和效率，预计2027年全球推行。",
    "content": "雅思官方宣布引入AI辅助口语评分系统，与人工评分相结合，提高评分一致性和效率，预计2027年全球推行。",
    "category": "英语学习",
    "source": "IELTS Official",
    "date": "2026-06-17",
    "icon": "📝",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": true
  },
  {
    "id": "eng-2",
    "title": "DeepL推出AI英语学习功能：实时纠错",
    "summary": "DeepL发布全新英语学习模块，利用大模型技术提供实时语法纠错、同义词推荐和语境化学习建议。",
    "content": "DeepL发布全新英语学习模块，利用大模型技术提供实时语法纠错、同义词推荐和语境化学习建议。",
    "category": "英语学习",
    "source": "DeepL",
    "date": "2026-06-17",
    "icon": "🌐",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  },
  {
    "id": "eng-3",
    "title": "牛津词典2026年度词汇候选：'Neuroplasticity'入围",
    "summary": "牛津词典公布2026年度词汇候选名单，'Neuroplasticity'（神经可塑性）等科学词汇入围，反映公众对脑科学关注。",
    "content": "牛津词典公布2026年度词汇候选名单，'Neuroplasticity'（神经可塑性）等科学词汇入围，反映公众对脑科学关注。",
    "category": "英语学习",
    "source": "Oxford Dictionary",
    "date": "2026-06-17",
    "icon": "📖",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": true
  },
  {
    "id": "eng-4",
    "title": "多邻国AI对话教练：模拟真实场景练口语",
    "summary": "Duolingo发布AI对话教练功能，利用GPT-4技术模拟餐厅点餐、面试等真实场景，提供个性化反馈。",
    "content": "Duolingo发布AI对话教练功能，利用GPT-4技术模拟餐厅点餐、面试等真实场景，提供个性化反馈。",
    "category": "英语学习",
    "source": "Duolingo",
    "date": "2026-06-17",
    "icon": "🦉",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  },
  {
    "id": "eng-5",
    "title": "研究：双语者阿尔茨海默病发病延迟5年",
    "summary": "剑桥大学最新研究表明，熟练掌握双语的人群阿尔茨海默病发病时间平均延迟4-5年，学习语言有益大脑健康。",
    "content": "剑桥大学最新研究表明，熟练掌握双语的人群阿尔茨海默病发病时间平均延迟4-5年，学习语言有益大脑健康。",
    "category": "英语学习",
    "source": "Cambridge University",
    "date": "2026-06-17",
    "icon": "🧠",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  }
],
  tech: [
  {
    "id": "tech-1",
    "title": "GrapheneOS has been ported to Android 17",
    "summary": "HackerNews 热门讨论，635 赞同，278 条评论。",
    "content": "HackerNews 热门讨论，635 赞同，278 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://discuss.grapheneos.org/d/36469-grapheneos-has-been-ported-to-android-17-and-official-releases-are-coming-soon",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-2",
    "title": "Running local models is good now",
    "summary": "HackerNews 热门讨论，1215 赞同，485 条评论。",
    "content": "HackerNews 热门讨论，1215 赞同，485 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://vickiboykis.com/2026/06/15/running-local-models-is-good-now/",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-3",
    "title": "DOJ claims xAI's gas turbines are a matter of 'national and energy security'",
    "summary": "HackerNews 热门讨论，64 赞同，37 条评论。",
    "content": "HackerNews 热门讨论，64 赞同，37 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://techcrunch.com/2026/06/16/doj-claims-xais-unpermitted-gas-turbines-are-a-matter-of-national-economic-and-energy-security/",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-4",
    "title": "Humiliating IIS servers for fun and jail time",
    "summary": "HackerNews 热门讨论，201 赞同，49 条评论。",
    "content": "HackerNews 热门讨论，201 赞同，49 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://mll.sh/humiliating-iis-servers-for-fun-and-jail-time/",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-5",
    "title": "Wolfram Language and Mathematica Version 15, AI Assistant, Symbolic Music, More",
    "summary": "HackerNews 热门讨论，146 赞同，62 条评论。",
    "content": "HackerNews 热门讨论，146 赞同，62 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://writings.stephenwolfram.com/2026/06/launching-version-15-of-wolfram-language-mathematica-built-in-useful-ai-lots-of-new-core-functionality/",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-6",
    "title": "TIL: You can make HTTP requests without curl using Bash /dev/TCP",
    "summary": "HackerNews 热门讨论，371 赞同，168 条评论。",
    "content": "HackerNews 热门讨论，371 赞同，168 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://mareksuppa.com/til/bash-dev-tcp-http-without-curl/",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-7",
    "title": "Calvin and Hobbes and the price of integrity",
    "summary": "HackerNews 热门讨论，374 赞同，166 条评论。",
    "content": "HackerNews 热门讨论，374 赞同，166 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://therepublicofletters.substack.com/p/calvin-and-hobbes-and-the-price-of",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-8",
    "title": "GPT‑NL: a sovereign language model for the Netherlands",
    "summary": "HackerNews 热门讨论，188 赞同，169 条评论。",
    "content": "HackerNews 热门讨论，188 赞同，169 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-17",
    "icon": "💻",
    "url": "https://www.tno.nl/en/digital/artificial-intelligence/gpt-nl/",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  science: [
  {
    "id": "sci-1",
    "title": "What is El Niño and why could it mean record temperatures?",
    "summary": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "content": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cj97npgk92po?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-2",
    "title": "El Niño under way and threatens weather extremes, scientists say",
    "summary": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "content": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/c75ylx7g00xo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-3",
    "title": "Six ways to keep your home and yourself cool in hot weather",
    "summary": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "content": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cz6gxe61p70o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-4",
    "title": "Nasa names next astronauts for Artemis Moon programme",
    "summary": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "content": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cdejn0gj12go?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-5",
    "title": "Nasa has named the Artemis III crew - what is their mission?",
    "summary": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "content": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cr5j40ezgz4o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-6",
    "title": "Rare footage captured of Great White shark in Mediterranean Sea",
    "summary": "A volunteer diver has described shaking as he filmed his encounter with an endangered Great White shark between Tunisia and Sicily.",
    "content": "A volunteer diver has described shaking as he filmed his encounter with an endangered Great White shark between Tunisia and Sicily.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/videos/cd6p6zqzj6do?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  knowledge: [
  {
    "id": "know-1",
    "title": "What is El Niño and why could it mean record temperatures?",
    "summary": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "content": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cj97npgk92po?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-2",
    "title": "El Niño under way and threatens weather extremes, scientists say",
    "summary": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "content": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/c75ylx7g00xo?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-3",
    "title": "Six ways to keep your home and yourself cool in hot weather",
    "summary": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "content": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cz6gxe61p70o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-4",
    "title": "Nasa names next astronauts for Artemis Moon programme",
    "summary": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "content": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cdejn0gj12go?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-5",
    "title": "Nasa has named the Artemis III crew - what is their mission?",
    "summary": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "content": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cr5j40ezgz4o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-6",
    "title": "Rare footage captured of Great White shark in Mediterranean Sea",
    "summary": "A volunteer diver has described shaking as he filmed his encounter with an endangered Great White shark between Tunisia and Sicily.",
    "content": "A volunteer diver has described shaking as he filmed his encounter with an endangered Great White shark between Tunisia and Sicily.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-17",
    "icon": "📚",
    "url": "https://www.bbc.com/news/videos/cd6p6zqzj6do?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  }
],
  sports: [
  {
    "id": "sport-1",
    "title": "世界杯-阿根廷首战3-0阿尔及利亚 梅西戴帽创纪录",
    "summary": "网易体育6月17日报道：北京时间6月17日上午9点，2026",
    "content": "网易体育6月17日报道：北京时间6月17日上午9点，2026",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/KVKCN49S00058781.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-2",
    "title": "世界杯-法国3-1复仇塞内加尔 姆巴佩世界波+双响",
    "summary": "网易体育6月17日报道：北京时间6月17日凌晨3点整，202",
    "content": "网易体育6月17日报道：北京时间6月17日凌晨3点整，202",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/KVJOCNH200058781.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-3",
    "title": "哈兰德14分钟双响！挪威队史首人，射手榜追平姆总，门将超巨失误",
    "summary": "世界杯小组赛第一轮，挪威对阵伊拉克。首次出战世界杯，哈兰德在",
    "content": "世界杯小组赛第一轮，挪威对阵伊拉克。首次出战世界杯，哈兰德在",
    "category": "体育",
    "source": "奥拜尔",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-4",
    "title": "歌手苏醒称赞梅西：卧槽疯了， 奔四了来刷射手榜了！",
    "summary": "北京时间6月17日上午，世界杯小组赛第一轮，阿根廷对阵阿尔及",
    "content": "北京时间6月17日上午，世界杯小组赛第一轮，阿根廷对阵阿尔及",
    "category": "体育",
    "source": "懂球帝",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-5",
    "title": "亚历山大回归耐克品牌旗下！官方声明：两届MVP将续写新篇章",
    "summary": "北京时间6月17日，Complex媒体确认：雷霆球星亚历山大",
    "content": "北京时间6月17日，Complex媒体确认：雷霆球星亚历山大",
    "category": "体育",
    "source": "罗说NBA",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-6",
    "title": "亚洲球队首负！7战2胜4平1负，伊拉克四连败，仍获赞亚洲雄风",
    "summary": "在伊拉克负于挪威之后，亚足联球队本届世界杯的不败纪录被终结。",
    "content": "在伊拉克负于挪威之后，亚足联球队本届世界杯的不败纪录被终结。",
    "category": "体育",
    "source": "奥拜尔",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-7",
    "title": "超级卧底?伊拉克后卫传球巨大失误 25岁哈兰德首秀暴砍2球+11连杀",
    "summary": "6月17日，世界杯小组赛继续进行，亚洲球队伊拉克对阵挪威队。",
    "content": "6月17日，世界杯小组赛继续进行，亚洲球队伊拉克对阵挪威队。",
    "category": "体育",
    "source": "风过乡",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-8",
    "title": "5年1.4亿！爵士给凯斯勒开出续约报价 湖人想抢人存在难度",
    "summary": "北京时间6月17日，根据ESPN名记TimMacMahon报",
    "content": "北京时间6月17日，根据ESPN名记TimMacMahon报",
    "category": "体育",
    "source": "醉卧浮生",
    "date": "2026-06-17",
    "icon": "🏀",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-9",
    "title": "梅西帽子戏法：纪录厚重，球王轻盈",
    "summary": "梅西帽子戏法。世界杯首战，个人世界杯第16个进球，追平历史第",
    "content": "梅西帽子戏法。世界杯首战，个人世界杯第16个进球，追平历史第",
    "category": "体育",
    "source": "张佳玮写字的地方",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-10",
    "title": "卫冕冠军阿根廷完美首秀，国窖 1573 定格历史瞬间",
    "summary": "北京时间2026年6月17日早上九点，世界杯小组赛J组第一轮",
    "content": "北京时间2026年6月17日早上九点，世界杯小组赛J组第一轮",
    "category": "体育",
    "source": "懂球帝",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-11",
    "title": "世界杯J组积分榜：阿根廷3-0大胜居首，奥地利3-1胜居次席",
    "summary": "北京时间6月17日，2026世界杯小组赛结束J组首轮的全部较",
    "content": "北京时间6月17日，2026世界杯小组赛结束J组首轮的全部较",
    "category": "体育",
    "source": "懂球帝",
    "date": "2026-06-17",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  entertainment: [
  {
    "id": "ent-1",
    "title": "百花奖名单惹争议，这5位实在可惜！",
    "summary": "6月16日，第38届大众电影百花奖正式公布了初评入围名单。消",
    "content": "6月16日，第38届大众电影百花奖正式公布了初评入围名单。消",
    "category": "娱乐",
    "source": "仙味少女心",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK8O3250556CHBI.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-2",
    "title": "40岁女歌手已离世！临终前自己定墓园和寿衣",
    "summary": "在阅读此文之前，辛苦您点击一下“关注”，既方便您进行讨论和分",
    "content": "在阅读此文之前，辛苦您点击一下“关注”，既方便您进行讨论和分",
    "category": "娱乐",
    "source": "可乐谈情感",
    "date": "2026-06-17",
    "icon": "🎵",
    "url": "https://3g.163.com/news/article/KVK9B3LM0553VGXP.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-3",
    "title": "向佐承认向太曾破坏他的恋情：她说了我就认",
    "summary": "向佐又上热搜了，这次不是因为武打戏，也不是因为综艺名场面，而",
    "content": "向佐又上热搜了，这次不是因为武打戏，也不是因为综艺名场面，而",
    "category": "娱乐",
    "source": "韩小娱",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK5UGVN0517U8SU.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-4",
    "title": "贝克汉姆夫妇受打击：布鲁克林拿自家事当段子",
    "summary": "最近贝克汉姆一家又上热搜了，这次不是因为谁穿得好看，也不是因",
    "content": "最近贝克汉姆一家又上热搜了，这次不是因为谁穿得好看，也不是因",
    "category": "娱乐",
    "source": "万国明信片",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK7GUR10556DBGY.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-5",
    "title": "汪海林为《给阿嫲的情书》正名：胜利属于人民",
    "summary": "最近影视圈最热闹、也最让人唏嘘的瓜，绝对绕不开《给阿嫲的情书",
    "content": "最近影视圈最热闹、也最让人唏嘘的瓜，绝对绕不开《给阿嫲的情书",
    "category": "娱乐",
    "source": "小徐讲八卦",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK87B9M0517JNH6.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-6",
    "title": "吴倩近照曝光变化太大，脖子前伸，脸也胖一圈",
    "summary": "前言2026年6月，沉寂许久的吴倩再度登上舆论热搜。一则“与",
    "content": "前言2026年6月，沉寂许久的吴倩再度登上舆论热搜。一则“与",
    "category": "娱乐",
    "source": "翰飞观事",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK88MRV055682OR.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-7",
    "title": "大S小行星命名，S妈骄傲发声：以你为荣",
    "summary": "6月16日，S妈黄春梅得知大S化成了一颗“星星”，骄傲发文：",
    "content": "6月16日，S妈黄春梅得知大S化成了一颗“星星”，骄傲发文：",
    "category": "娱乐",
    "source": "素素娱乐",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-8",
    "title": "筷子兄弟疯了？57岁王太利浓妆艳抹扮女装",
    "summary": "筷子兄弟疯了？57岁的王太利浓妆艳抹扮女装，一张嘴，差点把人",
    "content": "筷子兄弟疯了？57岁的王太利浓妆艳抹扮女装，一张嘴，差点把人",
    "category": "娱乐",
    "source": "西楼知趣杂谈",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK78RRJ055626SR.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-9",
    "title": "28岁韩国女星改行开整容医院！亲吐真实心声",
    "summary": "韩国娱乐圈向来不缺“一夜成名”的神话，但在耀眼聚光灯背后，也",
    "content": "韩国娱乐圈向来不缺“一夜成名”的神话，但在耀眼聚光灯背后，也",
    "category": "娱乐",
    "source": "好贤观史记",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK8G1QL0556C8KC.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-10",
    "title": "曹云金被曝深夜与3位美女相约，牛莉被牵连",
    "summary": "一组深夜聚餐图，曹云金再次冲向热搜。深夜十一点，一男三女，还",
    "content": "一组深夜聚餐图，曹云金再次冲向热搜。深夜十一点，一男三女，还",
    "category": "娱乐",
    "source": "大眼妹妹",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK7PQC205567KA5.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-11",
    "title": "与黄晓明离婚后，杨颖背后的男人是有妻女的他",
    "summary": "娱乐圈里什么最难？不是爆红，是在跌到谷底之后还能爬起来。杨颖",
    "content": "娱乐圈里什么最难？不是爆红，是在跌到谷底之后还能爬起来。杨颖",
    "category": "娱乐",
    "source": "枫尘余往逝",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK8ABQC0556CKUM.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-12",
    "title": "向佐表示父母不该公开说向佑:为什么不私下解决",
    "summary": "据6月17日报道，最近，向佐在一段访谈中罕见提及弟弟向佑，一",
    "content": "据6月17日报道，最近，向佐在一段访谈中罕见提及弟弟向佑，一",
    "category": "娱乐",
    "source": "韩小娱",
    "date": "2026-06-17",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVK6FTH00517U8SU.html",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  international: [
  {
    "id": "intl-1",
    "title": "Tehran selling deal with US as victory – but for Iranians it was necessity",
    "summary": "For many Iranians, the question is not whether the deal means victory, but whether it lowers prices and reduces fear of another war.",
    "content": "For many Iranians, the question is not whether the deal means victory, but whether it lowers prices and reduces fear of another war.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cn4rwzxvl8ko?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-2",
    "title": "Fragile quiet in Lebanon as US-Iran truce leaves unanswered questions",
    "summary": "Many Lebanese remain doubtful that the agreement could finally mean the end of the fighting between Israel and Hezbollah.",
    "content": "Many Lebanese remain doubtful that the agreement could finally mean the end of the fighting between Israel and Hezbollah.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cvgepl5gdp1o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-3",
    "title": "UK investigating reports Russian warship fired warning shots near yacht in English Channel",
    "summary": "The retired couple tell BBC Newsnight they tried to show the warship they had changed course in the English Channel before the shots were fired.",
    "content": "The retired couple tell BBC Newsnight they tried to show the warship they had changed course in the English Channel before the shots were fired.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c20yzm84r7lo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-4",
    "title": "Russian artist and Putin critic shot dead in Poland",
    "summary": "Robert Kuzovkov, who used the pseudonym Semyon Skrepetsky, has been known for his caricatures of politicians including Vladimir Putin.",
    "content": "Robert Kuzovkov, who used the pseudonym Semyon Skrepetsky, has been known for his caricatures of politicians including Vladimir Putin.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/clyrzd5g6k2o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-5",
    "title": "Brazil convicts Jair Bolsonaro's son of pursuing US help in father's legal battle",
    "summary": "Eduardo Bolsonaro called the conviction \"baseless and senseless\".",
    "content": "Eduardo Bolsonaro called the conviction \"baseless and senseless\".",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cgl3x0pey9lo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-6",
    "title": "German broadcaster removes TV intro after Elon Musk takes legal action",
    "summary": "ZDF TV responded to a \"cease and desist\" letter after the tech trillionaire condemned the broadcaster's \"outrageous lies\".",
    "content": "ZDF TV responded to a \"cease and desist\" letter after the tech trillionaire condemned the broadcaster's \"outrageous lies\".",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c0jyzp9z9deo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-7",
    "title": "Hundreds of cats stolen for food in Vietnam rescued by police, welfare group says",
    "summary": "Police have arrested nine people and rescued more than 400 cats destined for slaughter, with more than 40 reunited with their owners.",
    "content": "Police have arrested nine people and rescued more than 400 cats destined for slaughter, with more than 40 reunited with their owners.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c20yzm58vk3o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-8",
    "title": "France's oldest female detainee, 79, goes on trial for in-law's grisly murder",
    "summary": "A dismembered body found in a chain-bound trunk in the Seine in 1995 was only recently connected to the defendant by DNA evidence.",
    "content": "A dismembered body found in a chain-bound trunk in the Seine in 1995 was only recently connected to the defendant by DNA evidence.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cy498llene1o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-9",
    "title": "Venezuela signs deal with US energy giant to rebuild power grid",
    "summary": "The deal with General Electric is the latest sign of co-operation between US firms and Venezuela's interim government.",
    "content": "The deal with General Electric is the latest sign of co-operation between US firms and Venezuela's interim government.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c0jyzpv52yyo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-10",
    "title": "Eight dead after US Air Force B-52 bomber crashes in California",
    "summary": "The incident occurred on Monday morning while the aircraft had been on a routine test mission.",
    "content": "The incident occurred on Monday morning while the aircraft had been on a routine test mission.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cqx10yql319o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-11",
    "title": "'Dancing girl's' bare torso restored in Indian textbook after backlash",
    "summary": "A picture in a new school textbook had covered up the naked torso of the famous figurine with dark shading.",
    "content": "A picture in a new school textbook had covered up the naked torso of the famous figurine with dark shading.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c7vyzgl2142o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-12",
    "title": "Cuba tourism collapses as US pressure campaign bites",
    "summary": "The number of foreign visitors is down by 58% compared to last year, Cuban officials say, amid sanctions and an effective oil blockade.",
    "content": "The number of foreign visitors is down by 58% compared to last year, Cuban officials say, amid sanctions and an effective oil blockade.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-17",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/ckg8zrm20jjo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  history: [
    { id: 'his-1', title: '经典论文回顾：Attention Is All You Need（2017）', summary: 'Transformer架构的开创性论文，彻底改变了NLP领域，奠定了现代大语言模型的基础，被引用超过15万次。', category: '经典回顾', source: 'arXiv', date: '2017-06-12', icon: '📄', url: 'https://arxiv.org/abs/1706.03762', readTime: '15 分钟', isHot: false },
    { id: 'his-2', title: '经典论文回顾：ImageNet Classification with Deep CNN（2012）', summary: 'AlexNet论文，深度学习在计算机视觉领域的里程碑，首次证明深度CNN在图像识别中的巨大优势。', category: '经典回顾', source: 'NeurIPS', date: '2012-12-03', icon: '📷', url: 'https://papers.nips.cc', readTime: '12 分钟', isHot: false },
    { id: 'his-3', title: '经典著作：本杰明·格雷厄姆《聪明的投资者》（1949）', summary: '价值投资圣经，巴菲特称之为有史以来最好的投资书籍，阐述了安全边际、市场先生等核心理念。', category: '经典回顾', source: 'Harper & Brothers', date: '1949-01-01', icon: '📚', url: 'https://www.amazon.com', readTime: '30 分钟', isHot: false },
    { id: 'his-4', title: '里程碑：AlphaGo击败李世石（2016）', summary: 'DeepMind的AlphaGo以4:1击败世界围棋冠军李世石，标志着AI在复杂策略游戏中超越人类。', category: '经典回顾', source: 'Nature', date: '2016-03-15', icon: '⚫', url: 'https://www.nature.com', readTime: '10 分钟', isHot: false },
    { id: 'his-5', title: '经典论文回顾：Bitcoin白皮书（2008）', summary: '中本聪发布的比特币白皮书，开创了加密货币和区块链技术的新纪元，彻底改变了金融科技领域。', category: '经典回顾', source: 'Bitcoin.org', date: '2008-10-31', icon: '₿', url: 'https://bitcoin.org/bitcoin.pdf', readTime: '20 分钟', isHot: false },
    { id: 'his-6', title: '经典著作：瑞·达利欧《原则》（2017）', summary: '桥水基金创始人瑞·达利欧分享其生活与工作原则，包括极度求真、极度透明等核心理念，影响深远。', category: '经典回顾', source: 'Simon & Schuster', date: '2017-09-19', icon: '📖', url: 'https://www.principles.com', readTime: '25 分钟', isHot: false }
  ]
};

const hotTopics = [
  {
    "rank": 1,
    "title": "吴清：证监会打击违法违规跨境展业，支持投资者依法合规跨境投资活动",
    "category": "财经股市",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 2,
    "title": "野村：当前财季批发业务收入增长30% 主要受股票产品推动",
    "category": "财经股市",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 3,
    "title": "英国5月通胀率意外持稳于2.8% 支持央行采取观望策略",
    "category": "财经股市",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 4,
    "title": "六连冠！文远知行再度刷新中国智驾大赛连胜纪录",
    "category": "AI 技术",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 5,
    "title": "天工3.1 重磅发布：上线 Skywork Design 与 Dynamic Workflows，给 AI 一张画布和一支军团",
    "category": "AI 技术",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 6,
    "title": "刚刚，Fable-5之下，智谱开源的GLM-5.2拿下AI编程第一！",
    "category": "AI 技术",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 7,
    "title": "英特尔晒出未来芯片”三张底牌”：CFET、氮化镓+硅集成、钌互连",
    "category": "AI 技术",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 8,
    "title": "GrapheneOS has been ported to Android 17",
    "category": "计算机",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 9,
    "title": "Running local models is good now",
    "category": "计算机",
    "time": "2026-06-17",
    "hot": true
  },
  {
    "rank": 10,
    "title": "DOJ claims xAI's gas turbines are a matter of 'national and energy security'",
    "category": "计算机",
    "time": "2026-06-17",
    "hot": true
  }
];

const wordData = [
  { word: 'serendipity', phonetic: '/ˌser.ənˈdɪp.ə.ti/', meaning: '意外发现珍宝的运气；机缘凑巧', example: 'The discovery of penicillin was a moment of pure serendipity.', exampleTrans: '青霉素的发现纯粹是机缘巧合。' },
  { word: 'ephemeral', phonetic: '/ɪˈfem.ər.əl/', meaning: '短暂的；转瞬即逝的', example: 'Fashion is ephemeral, changing with every season.', exampleTrans: '时尚是短暂的，每季都在变化。' },
  { word: 'resilience', phonetic: '/rɪˈzɪl.jəns/', meaning: '韧性；恢复力；弹力', example: 'The resilience of the economy surprised many analysts.', exampleTrans: '经济的韧性让许多分析师感到惊讶。' },
  { word: 'paradigm', phonetic: '/ˈpær.ə.daɪm/', meaning: '典范；范例；模式', example: 'The new research represents a paradigm shift in our understanding.', exampleTrans: '这项新研究代表了我们在理解上的范式转变。' },
  { word: 'ubiquitous', phonetic: '/juːˈbɪk.wɪ.təs/', meaning: '无处不在的；十分普遍的', example: 'Smartphones have become ubiquitous in modern society.', exampleTrans: '智能手机在现代社会已经无处不在。' },
  { word: 'pragmatic', phonetic: '/præɡˈmæt.ɪk/', meaning: '务实的；实用的', example: 'We need a pragmatic approach to solve this problem.', exampleTrans: '我们需要一种务实的方法来解决这个问题。' },
  { word: 'innovation', phonetic: '/ˌɪn.əˈveɪ.ʃən/', meaning: '创新；革新；新方法', example: 'Technological innovation drives economic growth.', exampleTrans: '技术创新推动经济增长。' },
  { word: 'sustainable', phonetic: '/səˈsteɪ.nə.bəl/', meaning: '可持续的；能长期维持的', example: 'We must develop sustainable energy solutions.', exampleTrans: '我们必须开发可持续的能源解决方案。' },
  { word: 'algorithm', phonetic: '/ˈæl.ɡə.rɪ.ðəm/', meaning: '算法；计算程序', example: 'The recommendation algorithm personalizes content for each user.', exampleTrans: '推荐算法为每个用户个性化内容。' },
  { word: 'collaboration', phonetic: '/kəˌlæb.əˈreɪ.ʃən/', meaning: '合作；协作', example: 'International collaboration is essential for climate action.', exampleTrans: '国际合作对于气候行动至关重要。' }
];

const sentenceData = [
  { en: 'The only way to do great work is to love what you do.', cn: '成就伟大工作的唯一途径是热爱你所做的事。', source: 'Steve Jobs', tag: '励志' },
  { en: 'Innovation distinguishes between a leader and a follower.', cn: '创新决定一个人是领袖还是跟随者。', source: 'Steve Jobs', tag: '创新' },
  { en: 'The future belongs to those who believe in the beauty of their dreams.', cn: '未来属于那些相信梦想之美的人。', source: 'Eleanor Roosevelt', tag: '梦想' },
  { en: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', cn: '成功不是终点，失败也不是末日：继续前进的勇气才是最重要的。', source: 'Winston Churchill', tag: '坚持' },
  { en: 'The best time to plant a tree was 20 years ago. The second best time is now.', cn: '种一棵树最好的时间是二十年前，其次是现在。', source: 'Chinese Proverb', tag: '行动' },
  { en: 'In the middle of difficulty lies opportunity.', cn: '困境之中蕴藏着机遇。', source: 'Albert Einstein', tag: '机遇' },
  { en: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', cn: '生命中最伟大的荣耀不在于从不跌倒，而在于每次跌倒后都能站起来。', source: 'Nelson Mandela', tag: '坚韧' },
  { en: 'It does not matter how slowly you go as long as you do not stop.', cn: '只要你不停止，走得多慢都没关系。', source: 'Confucius', tag: '毅力' }
];

const newsVocabData = [
  { word: 'surge', meaning: '激增；暴涨', context: 'Stock prices surged after the earnings report.' },
  { word: 'volatile', meaning: '波动的；不稳定的', context: 'The market remains volatile amid geopolitical tensions.' },
  { word: 'merger', meaning: '合并；兼并', context: 'The merger between the two tech giants was approved.' },
  { word: 'dividend', meaning: '股息；红利', context: 'The company announced a quarterly dividend of $0.50.' },
  { word: 'recession', meaning: '经济衰退', context: 'Economists debate whether a recession is imminent.' },
  { word: 'inflation', meaning: '通货膨胀', context: 'Inflation cooled to 2.5% in the latest report.' },
  { word: 'bullish', meaning: '看涨的；乐观的', context: 'Analysts are bullish on AI stocks this quarter.' },
  { word: 'bearish', meaning: '看跌的；悲观的', context: 'Some investors remain bearish on the housing market.' },
  { word: 'liquidity', meaning: '流动性', context: 'The central bank injected liquidity into the market.' },
  { word: 'portfolio', meaning: '投资组合', context: 'Diversification is key to a healthy portfolio.' },
  { word: 'benchmark', meaning: '基准；标杆', context: 'The fund outperformed its benchmark by 3%.' },
  { word: 'valuation', meaning: '估值', context: "The startup's valuation reached $10 billion." }
];
