// Smart Daily 全站数据 - 自动生成于 2026-06-14 06:23
// 数据来源：新浪财经、网易新闻、量子位、HackerNews、GitHub、BBC News
const newsData = {
  updateTime: '2026-06-14 06:23',
  ai: [
  {
    "id": "ai-1",
    "title": "HuggingFace CEO力荐，Bengio团队也押注：这个1500美元训出的HRM模型，凭什么火了？",
    "summary": "模型参数量只有1B",
    "content": "模型参数量只有1B",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435483.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-2",
    "title": "Agent终于长出了身体：Jiuwen Symbiosis背后的思考与实践",
    "summary": "一起构建下一代物理世界的智能系统",
    "content": "一起构建下一代物理世界的智能系统",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435455.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-3",
    "title": "2026智源大会开幕：推动AI、物理世界和生命科学“三体互动”",
    "summary": "",
    "content": "",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435394.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-4",
    "title": "马斯克远程敲钟穿了老黄的皮衣！SpaceX员工集体穿上绿鞋",
    "summary": "马斯克成人类历史首位万亿美金富豪",
    "content": "马斯克成人类历史首位万亿美金富豪",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435339.html",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "ai-5",
    "title": "神了，世界杯第一天真按千问剧本踢了",
    "summary": "比分、红牌、绝杀全押中",
    "content": "比分、红牌、绝杀全押中",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435321.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-6",
    "title": "千里收购了一家毫米波雷达公司",
    "summary": "布局全栈闭环",
    "content": "布局全栈闭环",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435196.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-7",
    "title": "耐心资本护航创新，2026SuperLink开启创投价值共生新时代",
    "summary": "助力LP与GP高效合",
    "content": "助力LP与GP高效合",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435192.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-8",
    "title": "Anthropic老大的唯一 -1，就是AI股神的未婚妻",
    "summary": "那位被OpenAI开除的股神",
    "content": "那位被OpenAI开除的股神",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/433717.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-9",
    "title": "2026奇点智能产品大会首批嘉宾官宣：在 AI 的“可交付的时代”，看一线专家如何拆解真实落地闭环！",
    "summary": "7 月 17-18 日",
    "content": "7 月 17-18 日",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/435105.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "ai-10",
    "title": "“智能体最后的考试”，Fable 5竟然不敌GPT 5.5",
    "summary": "最难档通通零蛋",
    "content": "最难档通通零蛋",
    "category": "AI 技术",
    "source": "量子位",
    "date": "2026-06-14",
    "icon": "🤖",
    "url": "https://www.qbitai.com/2026/06/434774.html",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  finance: [
  {
    "id": "fin-1",
    "title": "鲁比奥回应印度的抗议 为封锁霍尔木兹海峡进行辩护",
    "summary": " 面对印度的抗议，美国国务卿马尔科·鲁比奥捍卫了华盛顿在霍尔木兹海峡的立场。此前美国空袭导致三名来自这个南亚国家的船员丧生。",
    "content": " 面对印度的抗议，美国国务卿马尔科·鲁比奥捍卫了华盛顿在霍尔木兹海峡的立场。此前美国空袭导致三名来自这个南亚国家的船员丧生。",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/world/2026-06-14/doc-iniciymx9128900.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-2",
    "title": "花旗银行：世界杯或将为金融市场带来短暂平静",
    "summary": "中东局势冲突、美联储可能加息，再加上市场波动加剧，这些因素让投资者始终紧绷神经。 不过花旗银行认为，正在进行的国际足联世界杯有望暂时降低市场波动。",
    "content": "中东局势冲突、美联储可能加息，再加上市场波动加剧，这些因素让投资者始终紧绷神经。 不过花旗银行认为，正在进行的国际足联世界杯有望暂时降低市场波动。",
    "category": "财经股市",
    "source": "环球市场播报",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-06-14/doc-iniciymw7573099.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-3",
    "title": "药明康德于6月12日斥资2.89亿港元回购230.12万股",
    "summary": "药明康德（02359）发布公告，该公司于2026年6月12日斥资2.89亿港元回购230.12万股股份，每股回购价格为121.2-127.3港元；及斥资1亿元人民币回购101.86万股A股...",
    "content": "药明康德（02359）发布公告，该公司于2026年6月12日斥资2.89亿港元回购230.12万股股份，每股回购价格为121.2-127.3港元；及斥资1亿元人民币回购101.86万股A股...",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/ggscyd/2026-06-14/doc-iniciymw7564990.shtml",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "fin-4",
    "title": "绿科科技国际：第一上海融资有限公司获委任为独立财务顾问",
    "summary": "绿科科技国际（00195）发布公告，本公司已根据收购守则规则2.1及规则2.8成立董事会辖下的独立董事委员会，以就部分收购要约向合资格股东提供意见。",
    "content": "绿科科技国际（00195）发布公告，本公司已根据收购守则规则2.1及规则2.8成立董事会辖下的独立董事委员会，以就部分收购要约向合资格股东提供意见。",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/ggscyd/2026-06-14/doc-iniciymz5887902.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-5",
    "title": "网易云音乐注销763.135万股库存股份",
    "summary": "网易云音乐（09899）公布，自2024年9月9日至2026年5月29日，公司根据2024年购回授权及2025年购回授权于香港联合交易所有限公司进行了一系列股份购回，并持作库存股份。",
    "content": "网易云音乐（09899）公布，自2024年9月9日至2026年5月29日，公司根据2024年购回授权及2025年购回授权于香港联合交易所有限公司进行了一系列股份购回，并持作库存股份。",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/ggscyd/2026-06-14/doc-iniciymw7564008.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-6",
    "title": "第七大道于6月12日斥资514.68万港元回购473万股",
    "summary": "第七大道（00797）发布公告，于2026年6月12日斥资514.68万港元回购473万股。",
    "content": "第七大道（00797）发布公告，于2026年6月12日斥资514.68万港元回购473万股。",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/ggscyd/2026-06-14/doc-iniciymz5886955.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-7",
    "title": "首程控股于6月12日斥资917.39万港元回购522万股",
    "summary": "首程控股（00697）发布公告，于2026年6月12日斥资917.39万港元回购522万股。",
    "content": "首程控股（00697）发布公告，于2026年6月12日斥资917.39万港元回购522万股。",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/ggscyd/2026-06-14/doc-iniciymx9110397.shtml",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "fin-8",
    "title": "信利国际于6月12日斥资191万港元回购200万股",
    "summary": "信利国际（00732）发布公告，该公司于2026年6月12日斥资191万港元回购200万股股份，每股回购价格为0.95-0.96港元。",
    "content": "信利国际（00732）发布公告，该公司于2026年6月12日斥资191万港元回购200万股股份，每股回购价格为0.95-0.96港元。",
    "category": "财经股市",
    "source": "新浪港股",
    "date": "2026-06-14",
    "icon": "📈",
    "url": "https://finance.sina.com.cn/stock/hkstock/ggscyd/2026-06-14/doc-iniciymv0785505.shtml",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  english: [
  {
    "id": "eng-1",
    "title": "2026年雅思考试改革：新增AI口语评估",
    "summary": "雅思官方宣布引入AI辅助口语评分系统，与人工评分相结合，提高评分一致性和效率，预计2027年全球推行。",
    "content": "雅思官方宣布引入AI辅助口语评分系统，与人工评分相结合，提高评分一致性和效率，预计2027年全球推行。",
    "category": "英语学习",
    "source": "IELTS Official",
    "date": "2026-06-14",
    "icon": "📝",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": true
  },
  {
    "id": "eng-2",
    "title": "DeepL推出AI英语学习功能：实时纠错",
    "summary": "DeepL发布全新英语学习模块，利用大模型技术提供实时语法纠错、同义词推荐和语境化学习建议。",
    "content": "DeepL发布全新英语学习模块，利用大模型技术提供实时语法纠错、同义词推荐和语境化学习建议。",
    "category": "英语学习",
    "source": "DeepL",
    "date": "2026-06-14",
    "icon": "🌐",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  },
  {
    "id": "eng-3",
    "title": "牛津词典2026年度词汇候选：'Neuroplasticity'入围",
    "summary": "牛津词典公布2026年度词汇候选名单，'Neuroplasticity'（神经可塑性）等科学词汇入围，反映公众对脑科学关注。",
    "content": "牛津词典公布2026年度词汇候选名单，'Neuroplasticity'（神经可塑性）等科学词汇入围，反映公众对脑科学关注。",
    "category": "英语学习",
    "source": "Oxford Dictionary",
    "date": "2026-06-14",
    "icon": "📖",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": true
  },
  {
    "id": "eng-4",
    "title": "多邻国AI对话教练：模拟真实场景练口语",
    "summary": "Duolingo发布AI对话教练功能，利用GPT-4技术模拟餐厅点餐、面试等真实场景，提供个性化反馈。",
    "content": "Duolingo发布AI对话教练功能，利用GPT-4技术模拟餐厅点餐、面试等真实场景，提供个性化反馈。",
    "category": "英语学习",
    "source": "Duolingo",
    "date": "2026-06-14",
    "icon": "🦉",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  },
  {
    "id": "eng-5",
    "title": "研究：双语者阿尔茨海默病发病延迟5年",
    "summary": "剑桥大学最新研究表明，熟练掌握双语的人群阿尔茨海默病发病时间平均延迟4-5年，学习语言有益大脑健康。",
    "content": "剑桥大学最新研究表明，熟练掌握双语的人群阿尔茨海默病发病时间平均延迟4-5年，学习语言有益大脑健康。",
    "category": "英语学习",
    "source": "Cambridge University",
    "date": "2026-06-14",
    "icon": "🧠",
    "url": "#",
    "readTime": "4 分钟",
    "isHot": false
  }
],
  tech: [
  {
    "id": "tech-1",
    "title": "Honda Civics and the Evil Valet",
    "summary": "HackerNews 热门讨论，201 赞同，32 条评论。",
    "content": "HackerNews 热门讨论，201 赞同，32 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "https://juniperspring.org/posts/honda-evil-valet/",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-2",
    "title": "Tribblix: The retro Illumos distribution",
    "summary": "HackerNews 热门讨论，13 赞同，3 条评论。",
    "content": "HackerNews 热门讨论，13 赞同，3 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "http://tribblix.org/",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-3",
    "title": "Pac-Man, but you're the ghost",
    "summary": "HackerNews 热门讨论，37 赞同，20 条评论。",
    "content": "HackerNews 热门讨论，37 赞同，20 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "https://garrit.xyz/posts/2026-06-13-pac-man-but-you-re-the-ghost",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "tech-4",
    "title": "Noise infusion banned from statistical products published by Census Bureau",
    "summary": "HackerNews 热门讨论，796 赞同，492 条评论。",
    "content": "HackerNews 热门讨论，796 赞同，492 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "https://desfontain.es/blog/banning-noise.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-5",
    "title": "GLM 5.2 Is Out",
    "summary": "HackerNews 热门讨论，483 赞同，265 条评论。",
    "content": "HackerNews 热门讨论，483 赞同，265 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "https://twitter.com/jietang/status/2065784751345287314",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-6",
    "title": "Every Frame Perfect",
    "summary": "HackerNews 热门讨论，653 赞同，212 条评论。",
    "content": "HackerNews 热门讨论，653 赞同，212 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "https://tonsky.me/blog/every-frame-perfect/",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-7",
    "title": "Building a serial and VGA \"everything console\"",
    "summary": "HackerNews 热门讨论，19 赞同，0 条评论。",
    "content": "HackerNews 热门讨论，19 赞同，0 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "http://oldvcr.blogspot.com/2026/06/building-serial-and-vga-everything.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "tech-8",
    "title": "FreeOberon – Open-Source, Cross-Platform, Free Pascal/Turbo Pascal-Like Language",
    "summary": "HackerNews 热门讨论，63 赞同，24 条评论。",
    "content": "HackerNews 热门讨论，63 赞同，24 条评论。",
    "category": "计算机",
    "source": "HackerNews",
    "date": "2026-06-14",
    "icon": "💻",
    "url": "https://github.com/kekcleader/FreeOberon",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  science: [
  {
    "id": "sci-1",
    "title": "烧烤店老板狂风暴雨中免单70多桌近3万元：安全最重要",
    "summary": "极目新闻记者张皓“对不住了，今天由于天气原因，棚子底下的今天",
    "content": "极目新闻记者张皓“对不住了，今天由于天气原因，棚子底下的今天",
    "category": "气象地质",
    "source": "极目新闻",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://3g.163.com/news/article/KVCR6J6J053469LG.html",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-2",
    "title": "What is El Niño and why could it mean record temperatures?",
    "summary": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "content": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cj97npgk92po?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-3",
    "title": "El Niño under way and threatens weather extremes, scientists say",
    "summary": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "content": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/c75ylx7g00xo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-4",
    "title": "Six ways to keep your home and yourself cool in hot weather",
    "summary": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "content": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cz6gxe61p70o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-5",
    "title": "Nasa names next astronauts for Artemis Moon programme",
    "summary": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "content": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cdejn0gj12go?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "sci-6",
    "title": "Nasa has named the Artemis III crew - what is their mission?",
    "summary": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "content": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "category": "气象地质",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "🔬",
    "url": "https://www.bbc.com/news/articles/cr5j40ezgz4o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  knowledge: [
  {
    "id": "know-1",
    "title": "What is El Niño and why could it mean record temperatures?",
    "summary": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "content": "Global temperatures are expected to rise in the coming months as El Niño begins.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cj97npgk92po?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-2",
    "title": "El Niño under way and threatens weather extremes, scientists say",
    "summary": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "content": "An El Niño event has officially started, say US scientists, raising fears of extreme weather and higher temperatures.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/c75ylx7g00xo?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-3",
    "title": "Six ways to keep your home and yourself cool in hot weather",
    "summary": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "content": "Six simple things you can do to help keep your house cool when temperatures rise.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cz6gxe61p70o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-4",
    "title": "Nasa names next astronauts for Artemis Moon programme",
    "summary": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "content": "Nasa names its next Artemis crew, though they will not be walking on the Moon or even going anywhere near it.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cdejn0gj12go?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-5",
    "title": "Nasa has named the Artemis III crew - what is their mission?",
    "summary": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "content": "Artemis III will help test crucial systems needed for the planned Artemis IV Moon landing in 2028.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "📚",
    "url": "https://www.bbc.com/news/articles/cr5j40ezgz4o?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  },
  {
    "id": "know-6",
    "title": "Rare footage captured of Great White shark in Mediterranean Sea",
    "summary": "A volunteer diver has described shaking as he filmed his encounter with an endangered Great White shark between Tunisia and Sicily.",
    "content": "A volunteer diver has described shaking as he filmed his encounter with an endangered Great White shark between Tunisia and Sicily.",
    "category": "知识科普",
    "source": "BBC Science",
    "date": "2026-06-14",
    "icon": "📚",
    "url": "https://www.bbc.com/news/videos/cd6p6zqzj6do?at_medium=RSS&at_campaign=rss",
    "readTime": "6 分钟",
    "isHot": false
  }
],
  sports: [
  {
    "id": "sport-1",
    "title": "8年8队夺冠，邓肯那句话，现在还给了马刺",
    "summary": "不出意外地，尼克斯顶住马刺天赋和联盟端水的压力，时隔53年捧",
    "content": "不出意外地，尼克斯顶住马刺天赋和联盟端水的压力，时隔53年捧",
    "category": "体育",
    "source": "后厂村体工队",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/KVCP78QI00059A81.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-2",
    "title": "尼克斯4-1马刺夺NBA总冠军 布伦森45分FMVP",
    "summary": "网易体育6月14日报道：NBA总决赛继续进行，纽约尼克斯队再",
    "content": "网易体育6月14日报道：NBA总决赛继续进行，纽约尼克斯队再",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-14",
    "icon": "🏀",
    "url": "https://m.163.com/sports/article/KVCN6V7U0005877U.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-3",
    "title": "世界杯-维尼修斯世界波救主 巴西首战1-1摩洛哥",
    "summary": "网易体育6月14日报道：北京时间6月14日上午6点，2026",
    "content": "网易体育6月14日报道：北京时间6月14日上午6点，2026",
    "category": "体育",
    "source": "网易体育",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "https://m.163.com/sports/article/KVCBI0PM00058781.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "sport-4",
    "title": "中国裁判本届世界杯首次执法！澳大利亚2比0战胜土耳其",
    "summary": "北京时间6月14日，美加墨世界杯D组首轮，连续第六次入围世界",
    "content": "北京时间6月14日，美加墨世界杯D组首轮，连续第六次入围世界",
    "category": "体育",
    "source": "澎湃新闻",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "https://3g.163.com/news/article/KVCVV7O00514R9P4.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-5",
    "title": "大变天！亚洲球队闪耀世界杯：3战欧洲队同时不败，压力给到日本",
    "summary": "北京时间6月14日下午，2026年美加墨世界杯首轮小组赛继续",
    "content": "北京时间6月14日下午，2026年美加墨世界杯首轮小组赛继续",
    "category": "体育",
    "source": "侃球熊弟",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-6",
    "title": "队史首分！卡塔尔1-1瑞士终结3连败 胡希读秒绝平救主",
    "summary": "本届世界杯正赛第3个比赛日，B小组首轮对决继续开战，世界排名",
    "content": "本届世界杯正赛第3个比赛日，B小组首轮对决继续开战，世界排名",
    "category": "体育",
    "source": "钉钉陌上花开",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-7",
    "title": "重磅！哈登非法携枪被捕已交保释金 6月22日开庭不定期接受尿检",
    "summary": "北京时间6月14日，当哈登在今年东决总分0-4被尼克斯横扫出",
    "content": "北京时间6月14日，当哈登在今年东决总分0-4被尼克斯横扫出",
    "category": "体育",
    "source": "醉卧浮生",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-8",
    "title": "昙花六现！张雪机车夺赛季第6冠 德比斯最后一圈反超+逆转绝杀",
    "summary": "北京时间6月13日，世界超级摩托车锦标赛意大利罗马涅站正赛第",
    "content": "北京时间6月13日，世界超级摩托车锦标赛意大利罗马涅站正赛第",
    "category": "体育",
    "source": "念洲",
    "date": "2026-06-13",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-9",
    "title": "被轰26脚 26岁门将5次神扑拯救卡塔尔 绝平后跪地痛哭+动情吻队徽",
    "summary": "在北京时间6月14日结束的世界杯B组首轮1场对决中，亚洲杯冠",
    "content": "在北京时间6月14日结束的世界杯B组首轮1场对决中，亚洲杯冠",
    "category": "体育",
    "source": "我爱英超",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-10",
    "title": "安切洛蒂不满！新闻发布会一团糟，听不清记者提问，当场质问FIFA",
    "summary": "在世界杯小组赛第一轮，巴西1比1战平摩洛哥。认为国际足联缺少",
    "content": "在世界杯小组赛第一轮，巴西1比1战平摩洛哥。认为国际足联缺少",
    "category": "体育",
    "source": "奥拜尔",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-11",
    "title": "澳大利亚2-0土耳其！苏塔超淡定，比奇开心挥手，土耳其低头沮丧",
    "summary": "澳大利亚2-0土耳其取得开门红。这场比赛澳大利亚的策略非常明",
    "content": "澳大利亚2-0土耳其取得开门红。这场比赛澳大利亚的策略非常明",
    "category": "体育",
    "source": "篮球资讯达人",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "sport-12",
    "title": "欧洲伪强队世界杯露馅 5亿豪阵狂轰30脚输0-2 9次大赛8度遭开门黑",
    "summary": "在北京时间6月14日结束的世界杯D组首轮1场对决中爆出冷门，",
    "content": "在北京时间6月14日结束的世界杯D组首轮1场对决中爆出冷门，",
    "category": "体育",
    "source": "我爱英超",
    "date": "2026-06-14",
    "icon": "⚽",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  entertainment: [
  {
    "id": "ent-1",
    "title": "具俊晔曝大S离世前虚弱照，难怪小s退让",
    "summary": "大S走了已经一年零四个多月，但真正让人破防的不是一个丈夫失去",
    "content": "大S走了已经一年零四个多月，但真正让人破防的不是一个丈夫失去",
    "category": "娱乐",
    "source": "情感大头说说",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCIC0JN055616Z7.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-2",
    "title": "因伤缺战！内马尔戴帽亮相，全身金首饰名表",
    "summary": "在北京时间6月14日结束的C组首轮一场对决中，首场“强强对话",
    "content": "在北京时间6月14日结束的C组首轮一场对决中，首场“强强对话",
    "category": "娱乐",
    "source": "我爱英超",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCEHPUG0529CA1F.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-3",
    "title": "去母留子？知名女演员遭老公小三上门暴打夺子",
    "summary": "怀胎十月一朝分娩，等来的不是丈夫的心疼怜惜，而是丈夫和小三的",
    "content": "怀胎十月一朝分娩，等来的不是丈夫的心疼怜惜，而是丈夫和小三的",
    "category": "娱乐",
    "source": "蹲坑看世界",
    "date": "2026-06-14",
    "icon": "⭐",
    "url": "https://3g.163.com/news/article/KVCDEPK905567KE9.html",
    "readTime": "3 分钟",
    "isHot": true
  },
  {
    "id": "ent-4",
    "title": "杜海涛为沈梦辰庆生，结婚4年无出被喊话！",
    "summary": "一个很反常识的画面——6月13日沈梦辰37岁生日，杜海涛零点",
    "content": "一个很反常识的画面——6月13日沈梦辰37岁生日，杜海涛零点",
    "category": "娱乐",
    "source": "小椰的奶奶",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCIEFGH0553TKE7.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-5",
    "title": "100岁卢燕获上影节终身成就奖",
    "summary": "6月13日晚，第28届上海国际电影节金爵盛典在上海大剧院举行",
    "content": "6月13日晚，第28届上海国际电影节金爵盛典在上海大剧院举行",
    "category": "娱乐",
    "source": "上观新闻",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCHHNLB055040N3.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-6",
    "title": "于娜32岁老公去世，成名作给了自己痛苦一击",
    "summary": "6月10日，一条热搜把无数人看愣了——45岁的于娜在芒果TV",
    "content": "6月10日，一条热搜把无数人看愣了——45岁的于娜在芒果TV",
    "category": "娱乐",
    "source": "可乐谈情感",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCIM6L40553VGXP.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-7",
    "title": "46岁郭京飞近况！娶鲍莉生下一子，成宠妻狂魔",
    "summary": "提起郭京飞，观众对他的印象鲜活又立体。他是荧幕上演技炸裂、自",
    "content": "提起郭京飞，观众对他的印象鲜活又立体。他是荧幕上演技炸裂、自",
    "category": "娱乐",
    "source": "代军哥哥谈娱乐",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCGJIO0051780D4.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-8",
    "title": "前无线首席新闻主播自曝曾被TVB编辑当众痛骂",
    "summary": "前TVB首席新闻女主播方健仪，昨天出现在观塘，担任HOY首档",
    "content": "前TVB首席新闻女主播方健仪，昨天出现在观塘，担任HOY首档",
    "category": "娱乐",
    "source": "TVB剧评社",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCGIN5G0517SNLE.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-9",
    "title": "本以为会离婚，却悄悄三胎，网友：错怪她了",
    "summary": "在这个热衷于给明星婚姻排期“领证”和“领证（离婚证）”的时代",
    "content": "在这个热衷于给明星婚姻排期“领证”和“领证（离婚证）”的时代",
    "category": "娱乐",
    "source": "史襉的生活科普",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCHAVM60556DLZ1.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-10",
    "title": "尼格买提离婚无儿女，撕开中年男性伪装面纱",
    "summary": "“钱不是万能的”这句话，在他身上体现的淋漓尽致，有钱也买不到",
    "content": "“钱不是万能的”这句话，在他身上体现的淋漓尽致，有钱也买不到",
    "category": "娱乐",
    "source": "生命之泉的奥秘",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCG25JG0556BNG2.html",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-11",
    "title": "《迷墙》最狠反派夫妻！为3000万彻底疯魔",
    "summary": "《迷墙》中最吓人的不仅仅是李槿，还有詹春和江娟这对看似人畜无",
    "content": "《迷墙》中最吓人的不仅仅是李槿，还有詹春和江娟这对看似人畜无",
    "category": "娱乐",
    "source": "电和影",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "",
    "readTime": "3 分钟",
    "isHot": false
  },
  {
    "id": "ent-12",
    "title": "温峥嵘回应乘风五公缺席！档期相撞实属无奈",
    "summary": "6月13日温峥嵘突然缺席《乘风2026》五公小考，瞬间引发全",
    "content": "6月13日温峥嵘突然缺席《乘风2026》五公小考，瞬间引发全",
    "category": "娱乐",
    "source": "阿废冷眼观察所",
    "date": "2026-06-14",
    "icon": "🎬",
    "url": "https://3g.163.com/news/article/KVCG6VVJ05566S1A.html",
    "readTime": "3 分钟",
    "isHot": false
  }
],
  international: [
  {
    "id": "intl-1",
    "title": "Trump says US-Iran deal to be signed on Sunday as Tehran casts doubt on timing",
    "summary": "The US president's comments come as Iran says an exact date has not been decided, but it \"will not be tomorrow\".",
    "content": "The US president's comments come as Iran says an exact date has not been decided, but it \"will not be tomorrow\".",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cvglmn49xz0o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-2",
    "title": "Switzerland votes on plan to cap population at 10 million",
    "summary": "The right-wing Swiss People's Party calls the plan a \"sustainability initiative\",  but opponents say it is a recipe for chaos.",
    "content": "The right-wing Swiss People's Party calls the plan a \"sustainability initiative\",  but opponents say it is a recipe for chaos.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cx23kz7e76po?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-3",
    "title": "Russian families use AI to 'resurrect' loved ones killed in Ukraine",
    "summary": "The highly controversial trend lies at the intersection of Russia's war on Ukraine, new AI technologies and grief.",
    "content": "The highly controversial trend lies at the intersection of Russia's war on Ukraine, new AI technologies and grief.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cwy24v72n19o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": true
  },
  {
    "id": "intl-4",
    "title": "New York Knicks win NBA championship for first time in over 50 years",
    "summary": "The Knicks clinched the title against the San Antonio Spurs, 94-90, in the fifth game of the best-of-seven series.",
    "content": "The Knicks clinched the title against the San Antonio Spurs, 94-90, in the fifth game of the best-of-seven series.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c78yw4zw19do?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-5",
    "title": "Nigerian author accuses hospital of stalling review into her son's death",
    "summary": "Chimamanda Ngozi Adichie's 21-month old son died in a Lagos hospital, which she says is trying to stop an inquest into the circumstances of his death.",
    "content": "Chimamanda Ngozi Adichie's 21-month old son died in a Lagos hospital, which she says is trying to stop an inquest into the circumstances of his death.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cgk6jzkr0xvo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-6",
    "title": "Vincent's parents 'never say he's good enough' - so he turned to a middle-aged couple online",
    "summary": "A niche group of content creators called \"virtual parents\" have become hugely popular among young people.",
    "content": "A niche group of content creators called \"virtual parents\" have become hugely popular among young people.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cpq3dnr5vlzo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-7",
    "title": "Norway braces for verdict in rape trial of crown princess's son Høiby",
    "summary": "Marius Borg Høiby will appear via video link, almost three months after his trial came to an end on 40 charges, including four counts of rape.",
    "content": "Marius Borg Høiby will appear via video link, almost three months after his trial came to an end on 40 charges, including four counts of rape.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cd95xvk4vn2o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-8",
    "title": "Woman seriously injured in shark attack at Sydney beach",
    "summary": "The woman, 35, was pulled from the water by members of the public and then airlifted to hospital, police say.",
    "content": "The woman, 35, was pulled from the water by members of the public and then airlifted to hospital, police say.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c3ryw807133o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-9",
    "title": "Trump's name removed from Kennedy Center after court order",
    "summary": "Crews erected scaffolding on Friday as onlookers gathered into the evening, though storms delayed the work until Saturday.",
    "content": "Crews erected scaffolding on Friday as onlookers gathered into the evening, though storms delayed the work until Saturday.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c5yzd4dgxw4o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-10",
    "title": "Married at First Sight Australia stars not told partners had drug and violence convictions",
    "summary": "Stars of the hit TV show say they did not know their on-screen husbands had previous convictions.",
    "content": "Stars of the hit TV show say they did not know their on-screen husbands had previous convictions.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/clypy0ndvjlo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-11",
    "title": "Kidnapped Nigerian retired general dies in captivity",
    "summary": "Maj Gen Rabe Abubakar's death highlights continuing security challenges facing parts of the country.",
    "content": "Maj Gen Rabe Abubakar's death highlights continuing security challenges facing parts of the country.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/cvgq4veq2eqo?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  },
  {
    "id": "intl-12",
    "title": "Anthropic suspends new AI tools over US government security concerns",
    "summary": "Anthropic's Claude Fable 5, released publicly this week, sparked concerns about cybersecurity and hacking.",
    "content": "Anthropic's Claude Fable 5, released publicly this week, sparked concerns about cybersecurity and hacking.",
    "category": "国际新闻",
    "source": "BBC News",
    "date": "2026-06-14",
    "icon": "🌍",
    "url": "https://www.bbc.com/news/articles/c932g3v3e13o?at_medium=RSS&at_campaign=rss",
    "readTime": "5 分钟",
    "isHot": false
  }
],
  history: [
    { id: 'his-1', title: '经典论文回顾：Attention Is All You Need（2017）', summary: 'Transformer架构的开创性论文，彻底改变了NLP领域，奠定了现代大语言模型的基础，被引用超过15万次。', category: '经典回顾', source: 'arXiv', date: '2017-06-12', icon: '📄', url: 'https://arxiv.org/abs/1706.03762', readTime: '15 分钟', isHot: false },
    { id: 'his-2', title: '经典论文回顾：ImageNet Classification with Deep CNN（2012）', summary: 'AlexNet论文，深度学习在计算机视觉领域的里程碑，首次证明深度CNN在图像识别中的巨大优势。', category: '经典回顾', source: 'NeurIPS', date: '2012-12-03', icon: '📷', url: 'https://papers.nips.cc', readTime: '12 分钟', isHot: false },
    { id: 'his-3', title: '经典著作：本杰明·格雷厄姆《聪明的投资者》（1949）', summary: '价值投资圣经，巴菲特称之为有史以来最好的投资书籍，阐述了安全边际、市场先生等核心理念。', category: '经典回顾', source: 'Harper & Brothers', date: '1949-01-01', icon: '📚', url: 'https://www.amazon.com', readTime: '30 分钟', isHot: false },
    { id: 'his-4', title: '里程碑：AlphaGo击败李世石（2016）', summary: 'DeepMind的AlphaGo以4:1击败世界围棋冠军李世石，标志着AI在复杂策略游戏中超越人类。', category: '经典回顾', source: 'Nature', date: '2016-03-15', icon: '⚫', url: 'https://www.nature.com', readTime: '10 分钟', isHot: false },
    { id: 'his-5', title: '经典论文回顾：Bitcoin白皮书（2008）', summary: '中本聪发布的比特币白皮书，开创了加密货币和区块链技术的新纪元，彻底改变了金融科技领域。', category: '经典回顾', source: 'Bitcoin.org', date: '2008-10-31', icon: '₿', url: 'https://bitcoin.org/bitcoin.pdf', readTime: '20 分钟', isHot: false },
    { id: 'his-6', title: '经典著作：瑞·达利欧《原则》（2017）', summary: '桥水基金创始人瑞·达利欧分享其生活与工作原则，包括极度求真、极度透明等核心理念，影响深远。', category: '经典回顾', source: 'Simon & Schuster', date: '2017-09-19', icon: '📖', url: 'https://www.principles.com', readTime: '25 分钟', isHot: false }
  ]
};

const hotTopics = [
  {
    "rank": 1,
    "title": "鲁比奥回应印度的抗议 为封锁霍尔木兹海峡进行辩护",
    "category": "财经股市",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 2,
    "title": "花旗银行：世界杯或将为金融市场带来短暂平静",
    "category": "财经股市",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 3,
    "title": "药明康德于6月12日斥资2.89亿港元回购230.12万股",
    "category": "财经股市",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 4,
    "title": "HuggingFace CEO力荐，Bengio团队也押注：这个1500美元训出的HRM模型，凭什么火了？",
    "category": "AI 技术",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 5,
    "title": "Agent终于长出了身体：Jiuwen Symbiosis背后的思考与实践",
    "category": "AI 技术",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 6,
    "title": "2026智源大会开幕：推动AI、物理世界和生命科学“三体互动”",
    "category": "AI 技术",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 7,
    "title": "马斯克远程敲钟穿了老黄的皮衣！SpaceX员工集体穿上绿鞋",
    "category": "AI 技术",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 8,
    "title": "Honda Civics and the Evil Valet",
    "category": "计算机",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 9,
    "title": "Tribblix: The retro Illumos distribution",
    "category": "计算机",
    "time": "2026-06-14",
    "hot": true
  },
  {
    "rank": 10,
    "title": "Pac-Man, but you're the ghost",
    "category": "计算机",
    "time": "2026-06-14",
    "hot": true
  }
];

const wordData = [
  { word: 'serendipity', phonetic: '/ˌser.ənˈdɪp.ə.ti/', meaning: '意外发现珍宝的运气；机缘凑巧', example: 'The discovery of penicillin was a moment of pure serendipity.', exampleTrans: '青霉素的发现纯粹是机缘巧合。' },
  { word: 'ephemeral', phonetic: '/ɪˈfem.ər.əl/', meaning: '短暂的；转瞬即逝的', example: 'Fashion is ephemeral, changing with every season.', exampleTrans: '时尚是短暂的，每季都在变化。' },
  { word: 'resilience', phonetic: '/rɪˈzɪl.jəns/', meaning: '韧性；恢复力；弹力', example: 'The resilience of the economy surprised many analysts.', exampleTrans: '经济的韧性让许多分析师感到惊讶。' },
  { word: 'paradigm', phonetic: '/ˈpær.ə.daɪm/', meaning: '典范；范例；模式', example: 'The new research represents a paradigm shift in our understanding.', exampleTrans: '这项新研究代表了我们在理解上的范式转变。' },
  { word: 'ubiquitous', phonetic: '/juːˈbɪk.wɪ.təs/', meaning: '无处不在的；十分普遍的', example: 'Smartphones have become ubiquitous in modern society.', exampleTrans: '智能手机在现代社会已经无处不在。' },
  { word: 'pragmatic', phonetic: '/præɡˈmæt.ɪk/', meaning: '务实的；实用的', example: 'We need a pragmatic approach to solve this problem.', exampleTrans: '我们需要一种务实的方法来解决这个问题。' },
  { word: 'innovation', phonetic: '/ˌɪn.əˈveɪ.ʃən/', meaning: '创新；革新；新方法', example: 'Technological innovation drives economic growth.', exampleTrans: '技术创新推动经济增长。' },
  { word: 'sustainable', phonetic: '/səˈsteɪ.nə.bəl/', meaning: '可持续的；能长期维持的', example: 'We must develop sustainable energy solutions.', exampleTrans: '我们必须开发可持续的能源解决方案。' },
  { word: 'algorithm', phonetic: '/ˈæl.ɡə.rɪ.ðəm/', meaning: '算法；计算程序', example: 'The recommendation algorithm personalizes content for each user.', exampleTrans: '推荐算法为每个用户个性化内容。' },
  { word: 'collaboration', phonetic: '/kəˌlæb.əˈreɪ.ʃən/', meaning: '合作；协作', example: 'International collaboration is essential for climate action.', exampleTrans: '国际合作对于气候行动至关重要。' }
];

const sentenceData = [
  { en: 'The only way to do great work is to love what you do.', cn: '成就伟大工作的唯一途径是热爱你所做的事。', source: 'Steve Jobs', tag: '励志' },
  { en: 'Innovation distinguishes between a leader and a follower.', cn: '创新决定一个人是领袖还是跟随者。', source: 'Steve Jobs', tag: '创新' },
  { en: 'The future belongs to those who believe in the beauty of their dreams.', cn: '未来属于那些相信梦想之美的人。', source: 'Eleanor Roosevelt', tag: '梦想' },
  { en: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', cn: '成功不是终点，失败也不是末日：继续前进的勇气才是最重要的。', source: 'Winston Churchill', tag: '坚持' },
  { en: 'The best time to plant a tree was 20 years ago. The second best time is now.', cn: '种一棵树最好的时间是二十年前，其次是现在。', source: 'Chinese Proverb', tag: '行动' },
  { en: 'In the middle of difficulty lies opportunity.', cn: '困境之中蕴藏着机遇。', source: 'Albert Einstein', tag: '机遇' },
  { en: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', cn: '生命中最伟大的荣耀不在于从不跌倒，而在于每次跌倒后都能站起来。', source: 'Nelson Mandela', tag: '坚韧' },
  { en: 'It does not matter how slowly you go as long as you do not stop.', cn: '只要你不停止，走得多慢都没关系。', source: 'Confucius', tag: '毅力' }
];

const newsVocabData = [
  { word: 'surge', meaning: '激增；暴涨', context: 'Stock prices surged after the earnings report.' },
  { word: 'volatile', meaning: '波动的；不稳定的', context: 'The market remains volatile amid geopolitical tensions.' },
  { word: 'merger', meaning: '合并；兼并', context: 'The merger between the two tech giants was approved.' },
  { word: 'dividend', meaning: '股息；红利', context: 'The company announced a quarterly dividend of $0.50.' },
  { word: 'recession', meaning: '经济衰退', context: 'Economists debate whether a recession is imminent.' },
  { word: 'inflation', meaning: '通货膨胀', context: 'Inflation cooled to 2.5% in the latest report.' },
  { word: 'bullish', meaning: '看涨的；乐观的', context: 'Analysts are bullish on AI stocks this quarter.' },
  { word: 'bearish', meaning: '看跌的；悲观的', context: 'Some investors remain bearish on the housing market.' },
  { word: 'liquidity', meaning: '流动性', context: 'The central bank injected liquidity into the market.' },
  { word: 'portfolio', meaning: '投资组合', context: 'Diversification is key to a healthy portfolio.' },
  { word: 'benchmark', meaning: '基准；标杆', context: 'The fund outperformed its benchmark by 3%.' },
  { word: 'valuation', meaning: '估值', context: "The startup's valuation reached $10 billion." }
];
